# Generated by Django 5.2.6 on 2025-11-10 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_measurement_taken_at_order_rider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Acceptance'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the assignment', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the rider accepted the order', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the rider started working on the order', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the rider completed the delivery', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from the rider', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='Order assigned to this rider', on_delete=django.db.models.deletion.CASCADE, related_name='rider_assignment', to='orders.order')),
                ('rider', models.ForeignKey(help_text='Rider assigned to this order', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Order Assignment',
                'verbose_name_plural': 'Rider Order Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, help_text='Full name of the rider', max_length=255, null=True)),
                ('national_id', models.CharField(blank=True, help_text='National ID or ID number', max_length=20, null=True, unique=True)),
                ('phone_number', models.CharField(help_text='Primary contact number', max_length=20)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=20, null=True)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('bicycle', 'Bicycle'), ('other', 'Other')], default='motorcycle', help_text='Type of vehicle used for delivery', max_length=50)),
                ('vehicle_number', models.CharField(blank=True, help_text='Vehicle registration number', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the rider is currently active')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the rider is currently available for new orders')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current latitude location', max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current longitude location', max_digits=9, null=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0, help_text='Total number of completed deliveries')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from customers', max_digits=3)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User account for this rider', on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Profile',
                'verbose_name_plural': 'Rider Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
