# Generated by Django 5.2.6 on 2025-11-10 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfileReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Review status of the rider profile', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the profile was submitted for review', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the profile was reviewed by admin', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(help_text='Rider profile being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='riders.riderprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rider_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Profile Review',
                'verbose_name_plural': 'Rider Profile Reviews',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
