# Generated by Django 5.2.6 on 2025-11-10 06:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_riderprofilereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, help_text='Insurance expiry date', null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='insurance_policy_number',
            field=models.CharField(blank=True, help_text='Insurance policy number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='insurance_provider',
            field=models.CharField(blank=True, help_text='Insurance provider name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='iqama_expiry_date',
            field=models.DateField(blank=True, help_text='Iqama / National ID expiry date', null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='iqama_number',
            field=models.CharField(blank=True, help_text='Iqama Number (10-digit) or Saudi National ID for citizens', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Iqama number must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_expiry_date',
            field=models.DateField(blank=True, help_text='Driving license expiry date', null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_number',
            field=models.CharField(blank=True, help_text='Driving license number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('general', 'General'), ('motorcycle', 'Motorcycle'), ('commercial', 'Commercial')], help_text='Type of driving license', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_color',
            field=models.CharField(blank=True, help_text='Vehicle color', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_make',
            field=models.CharField(blank=True, help_text='Vehicle make/brand (e.g., Toyota, Honda)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='Vehicle model (e.g., Camry, Accord)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_plate_number_arabic',
            field=models.CharField(blank=True, help_text='Vehicle plate number in Arabic', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_plate_number_english',
            field=models.CharField(blank=True, help_text='Vehicle plate number in English', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_registration_expiry_date',
            field=models.DateField(blank=True, help_text='Vehicle Registration (Istimara) expiry date', null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_registration_number',
            field=models.CharField(blank=True, help_text='Vehicle Registration (Istimara) Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_year',
            field=models.PositiveIntegerField(blank=True, help_text='Vehicle manufacturing year', null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('bicycle', 'Bicycle'), ('truck', 'Truck'), ('van', 'Van'), ('other', 'Other')], help_text='Type of vehicle used for delivery', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RiderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('iqama_front', 'Iqama Front'), ('iqama_back', 'Iqama Back'), ('license_front', 'Driving License Front'), ('license_back', 'Driving License Back'), ('istimara_front', 'Istimara Front'), ('istimara_back', 'Istimara Back'), ('insurance', 'Insurance Card')], help_text='Type of document', max_length=50)),
                ('document_image', models.ImageField(help_text='Document image (JPG, JPEG, PNG, PDF)', upload_to='rider_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this document has been verified by admin')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the document was verified', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider_profile', models.ForeignKey(help_text='Rider profile this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='riders.riderprofile')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_rider_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Document',
                'verbose_name_plural': 'Rider Documents',
                'ordering': ['-created_at'],
                'unique_together': {('rider_profile', 'document_type')},
            },
        ),
    ]
