# Generated by Django 5.2.5 on 2026-02-03 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_alter_riderprofile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailorInvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Unique invitation code (e.g., TAL-42-X7K9P)', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code can still be used')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Maximum number of times this code can be used (0 = unlimited)')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='How many times this code has been used')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this code expires (null = never)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tailor', models.ForeignKey(help_text='Tailor who created this invitation code', limit_choices_to={'role': 'TAILOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_invitation_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tailor Invitation Code',
                'verbose_name_plural': 'Tailor Invitation Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TailorRiderAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this association is currently active')),
                ('nickname', models.CharField(blank=True, help_text='Optional friendly name/nickname for this rider (set by tailor)', max_length=100)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority/ranking for this rider (higher = more preferred)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('joined_via_code', models.ForeignKey(blank=True, help_text='The invitation code used to join (for tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associations', to='riders.tailorinvitationcode')),
                ('rider', models.ForeignKey(help_text='Rider in this association', limit_choices_to={'role': 'RIDER'}, on_delete=django.db.models.deletion.CASCADE, related_name='associated_tailors', to=settings.AUTH_USER_MODEL)),
                ('tailor', models.ForeignKey(help_text='Tailor in this association', limit_choices_to={'role': 'TAILOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='associated_riders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tailor-Rider Association',
                'verbose_name_plural': 'Tailor-Rider Associations',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tailorinvitationcode',
            index=models.Index(fields=['code'], name='riders_tail_code_cbde8d_idx'),
        ),
        migrations.AddIndex(
            model_name='tailorinvitationcode',
            index=models.Index(fields=['tailor', 'is_active'], name='riders_tail_tailor__9a64b4_idx'),
        ),
        migrations.AddIndex(
            model_name='tailorriderassociation',
            index=models.Index(fields=['tailor', 'is_active'], name='riders_tail_tailor__3d1f03_idx'),
        ),
        migrations.AddIndex(
            model_name='tailorriderassociation',
            index=models.Index(fields=['rider', 'is_active'], name='riders_tail_rider_i_c658a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tailorriderassociation',
            unique_together={('tailor', 'rider')},
        ),
    ]
