# Generated by Django 5.2.6 on 2025-09-29 19:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0010_customerprofile_tags'),
        ('tailors', '0006_alter_fabric_fabric_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(editable=False, help_text='Unique order number generated automatically', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('measuring', 'Measuring'), ('cutting', 'Cutting'), ('stitching', 'Stitching'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='current status of the order', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='sub total before taxes and fees', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='delivery fee', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount including taxes and fees', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', help_text='Payment_status', max_length=20)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer')], default='credit_card', help_text='Payment method chosen by customer', max_length=20)),
                ('estimated_delivery_date', models.DateField(blank=True, help_text='Estimated delivery time', null=True)),
                ('actual_delivery_date', models.DateField(blank=True, help_text='Actual delivery time', null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions from customer', null=True)),
                ('notes', models.TextField(blank=True, help_text='Interal notes for tailor/admin', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='The customer who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_address', models.ForeignKey(blank=True, help_text='Delivery address for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='customers.address')),
                ('tailor', models.ForeignKey(help_text='Tailor assigned to this order', on_delete=django.db.models.deletion.CASCADE, related_name='tailor_orders', to='tailors.tailorprofile')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this fabric')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of order', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item (quantity × unit_price)', max_digits=10)),
                ('measurements', models.JSONField(blank=True, default=dict, help_text='Customer measurements for this item')),
                ('custom_instructions', models.TextField(blank=True, help_text='Custom instructions for this specific item', null=True)),
                ('is_ready', models.BooleanField(default=False, help_text='Whether this item is ready for delivery')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fabric', models.ForeignKey(help_text='Fabric beginf ordered', on_delete=django.db.models.deletion.CASCADE, to='tailors.fabric')),
                ('order', models.ForeignKey(help_text='Order this items belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('measuring', 'Measuring'), ('cutting', 'Cutting'), ('stitching', 'Stitching'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], help_text='Status that was set', max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('measuring', 'Measuring'), ('cutting', 'Cutting'), ('stitching', 'Stitching'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], help_text='Previous status before this change', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this status change', null=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made this status change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order this status change belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
