# Generated by Django 5.2.6 on 2025-11-10 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='measurement_taken_at',
            field=models.DateTimeField(blank=True, help_text='When measurements were taken by the rider', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, help_text='Rider assigned to this order for delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_measurements',
            field=models.JSONField(blank=True, default=dict, help_text='Measurements taken by rider at customer location (for fabric_with_stitching orders)', null=True),
        ),
    ]
