# Generated by Django 5.2.6 on 2025-09-30 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_created_by_alter_orderitem_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tailor',
            field=models.ForeignKey(help_text='Tailor assigned to this order', on_delete=django.db.models.deletion.CASCADE, related_name='tailor_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
