# Generated by Django 5.2.6 on 2025-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_measurement_taken_at_order_rider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointment_date',
            field=models.DateField(blank=True, help_text='Appointment date for customer (optional)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='appointment_time',
            field=models.TimeField(blank=True, help_text='Appointment time for customer (optional)', null=True),
        ),
    ]
