# Generated by Django 5.2.6 on 2025-10-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_tailor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('fabric_only', 'Fabric Purchase Only'), ('fabric_with_stitching', 'Fabric + Stitching')], default='fabric_with_stitching', help_text='Type of order - fabric only or fabric with stitching', max_length=25),
        ),
    ]
