# Generated by Django 5.2.6 on 2025-10-01 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customerprofile_tags'),
        ('orders', '0004_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='family_member',
            field=models.ForeignKey(blank=True, help_text='Family member this order is for (optional - if not specified, order is for the customer)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.familymember'),
        ),
    ]
