# Generated by Django 5.2.6 on 2025-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_custom_styles_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='custom_styles',
            field=models.JSONField(blank=True, default=None, help_text="Array of custom style selections (optional). Format: [{'style_type': 'collar', 'index': 0, 'label': 'Collar Style 1', 'asset_path': 'assets/thobs/collar/collar1.png'}]", null=True),
        ),
    ]
