# Generated by Django 5.2.6 on 2025-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_fix_custom_styles_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_status',
            field=models.CharField(choices=[('none', 'Not Assigned'), ('accepted', 'Accepted Order'), ('on_way_to_pickup', 'On Way to Pickup'), ('picked_up', 'Picked Up'), ('on_way_to_delivery', 'On Way to Delivery'), ('on_way_to_measurement', 'On Way to Measurement'), ('measurement_taken', 'Measurement Taken'), ('delivered', 'Delivered')], default='none', help_text='Current rider activity status', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='tailor_status',
            field=models.CharField(choices=[('none', 'None'), ('accepted', 'Accepted Order'), ('stitching_started', 'Started Stitching'), ('stitched', 'Finished Stitching')], default='none', help_text='Current tailor activity status', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Main status of the order', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], help_text='Previous status before this change', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], help_text='Status that was set', max_length=20),
        ),
    ]
