# Generated by Django 5.2.5 on 2025-12-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_rider_tailor_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tailor_status',
            field=models.CharField(choices=[('none', 'None'), ('accepted', 'Accepted Order'), ('in_progress', 'In Progress'), ('stitching_started', 'Started Stitching'), ('stitched', 'Finished Stitching')], default='none', help_text='Current tailor activity status', max_length=30),
        ),
    ]
