# Generated by Django 5.2.5 on 2025-12-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_add_address_remove_formatted_address'),
        ('orders', '0007_add_in_progress_to_tailor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='family_member',
            field=models.ForeignKey(blank=True, help_text='Family member this item is for (optional - if not specified, item is for the customer)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.familymember'),
        ),
    ]
