# Generated by Django 5.2.5 on 2025-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_family_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, help_text='Delivery city', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_extra_info',
            field=models.TextField(blank=True, help_text='Delivery extra info', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Delivery latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Delivery longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street',
            field=models.CharField(blank=True, help_text='Delivery street', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Delivery address', null=True),
        ),
    ]
