# Generated by Django 5.2.5 on 2025-12-21 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customerprofile_measurements'),
        ('orders', '0009_order_delivery_city_order_delivery_extra_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_formatted_address',
            field=models.TextField(blank=True, help_text='Formatted address from geocoding (current location)', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, help_text='Delivery address for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='customers.address'),
        ),
    ]
