# Generated by Django 5.2.5 on 2025-12-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_formatted_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rider_status',
            field=models.CharField(choices=[('none', 'Not Assigned'), ('accepted', 'Accepted Order'), ('on_way_to_pickup', 'On Way to Pickup'), ('picked_up', 'Picked Up'), ('on_way_to_delivery', 'On Way to Delivery'), ('on_way_to_measurement', 'On Way to Measurement'), ('measuring', 'Measuring'), ('measurement_taken', 'Measurement Taken'), ('delivered', 'Delivered')], default='none', help_text='Current rider activity status', max_length=30),
        ),
    ]
