# Generated by Django 5.2.5 on 2025-12-26 11:18

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_add_measuring_rider_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stitching_completion_date',
            field=models.DateField(blank=True, help_text='Stitching completition date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stitching_completion_time',
            field=models.TimeField(blank=True, help_text='Stitching completition time', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rider_status',
            field=django_fsm.FSMField(choices=[('none', 'Not Assigned'), ('accepted', 'Accepted Order'), ('on_way_to_pickup', 'On Way to Pickup'), ('picked_up', 'Picked Up'), ('on_way_to_delivery', 'On Way to Delivery'), ('on_way_to_measurement', 'On Way to Measurement'), ('measuring', 'Measuring'), ('measurement_taken', 'Measurement Taken'), ('delivered', 'Delivered')], default='none', help_text='Current rider activity status', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='tailor_status',
            field=django_fsm.FSMField(choices=[('none', 'None'), ('accepted', 'Accepted Order'), ('in_progress', 'In Progress'), ('stitching_started', 'Started Stitching'), ('stitched', 'Finished Stitching')], default='none', help_text='Current tailor activity status', max_length=30),
        ),
    ]
