# Generated by Django 5.2.5 on 2025-12-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_add_add_stitching_completion_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stitching_completion_date',
            field=models.DateField(blank=True, help_text='Stitching completion date', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stitching_completion_time',
            field=models.TimeField(blank=True, help_text='Stitching completion time', null=True),
        ),
    ]
