# Generated by Django 5.2.5 on 2026-01-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_stitching_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_mode',
            field=models.CharField(choices=[('home_delivery', 'Home Delivery'), ('walk_in', 'Walk-In Service')], default='home_delivery', help_text='Service mode - Home Delivery or Walk-In', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('ready_for_delivery', 'Ready for Delivery'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Delivered'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='pending', help_text='Main status of the order', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('ready_for_delivery', 'Ready for Delivery'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Delivered'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], help_text='Previous status before this change', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('ready_for_delivery', 'Ready for Delivery'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Delivered'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], help_text='Status that was set', max_length=20),
        ),
    ]
