# Generated by Django 5.2.5 on 2026-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_service_mode_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_free_measurement',
            field=models.BooleanField(default=False, help_text='Whether this is a free first-time measurement order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('fabric_only', 'Fabric Purchase Only'), ('fabric_with_stitching', 'Fabric + Stitching'), ('measurement_service', 'Measurement Service Only')], default='fabric_with_stitching', help_text='Type of order - fabric only or fabric with stitching', max_length=25),
        ),
    ]
