# Generated by Django 5.2.5 on 2026-01-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_add_measurement_service_fields'),
        ('tailors', '0003_fabric_stitching_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='fabric',
            field=models.ForeignKey(blank=True, help_text='Fabric beginf ordered', null=True, on_delete=django.db.models.deletion.CASCADE, to='tailors.fabric'),
        ),
    ]
