# Generated by Django 5.2.5 on 2026-01-06 17:01

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_make_tailor_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tailor_status',
            field=django_fsm.FSMField(choices=[('none', 'None'), ('accepted', 'Accepted Order'), ('in_progress', 'In Progress'), ('stitching_started', 'Started Stitching'), ('stitched', 'Finished Stitching'), ('measurements_complete', 'Measurements Complete')], default='none', help_text='Current tailor activity status', max_length=30),
        ),
    ]
