# Generated by Django

from django.db import migrations, models


def migrate_custom_styles_to_items(apps, schema_editor):
    """
    Migrate custom_styles from Order to OrderItem.
    
    Strategy:
    - For orders with single item: Copy styles directly to that item
    - For orders with multiple items: Copy styles to all items (safe default)
    - Handle null/empty custom_styles gracefully
    """
    Order = apps.get_model('orders', 'Order')
    OrderItem = apps.get_model('orders', 'OrderItem')
    
    # Get all orders with custom_styles data
    orders_with_styles = Order.objects.filter(custom_styles__isnull=False).exclude(custom_styles=[])
    
    migrated_count = 0
    for order in orders_with_styles:
        items = order.order_items.all()
        
        if not items.exists():
            # No items, skip
            continue
        
        if items.count() == 1:
            # Single item: Copy styles directly
            item = items.first()
            item.custom_styles = order.custom_styles
            item.save(update_fields=['custom_styles'])
            migrated_count += 1
        else:
            # Multiple items: Copy styles to all items
            # This is a safe default - frontend can later refine per-item styles
            for item in items:
                item.custom_styles = order.custom_styles
                item.save(update_fields=['custom_styles'])
            migrated_count += 1
    
    if migrated_count > 0:
        print(f"Migrated custom_styles for {migrated_count} orders to their OrderItems")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_stitching_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_styles',
            field=models.JSONField(blank=True, default=None, help_text="Custom style selections for this item. Format: [{'style_type': 'collar', 'index': 0, 'label': 'Collar Style 1', 'asset_path': 'assets/thobs/collar/collar1.png'}]", null=True),
        ),
        migrations.RunPython(
            migrate_custom_styles_to_items,
            reverse_code=migrations.RunPython.noop
        ),
    ]
