# Generated by Django 5.2.5 on 2026-02-14 04:59

import django_fsm
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_assigned_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='system_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed system fee (SAR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='tailor_status',
            field=django_fsm.FSMField(choices=[('none', 'New'), ('accepted', 'Accepted Order'), ('in_progress', 'In Progress'), ('stitching_started', 'Started Stitching'), ('stitched', 'Finished Stitching'), ('measurements_complete', 'Measurements Complete')], default='none', help_text='Current tailor activity status', max_length=30),
        ),
    ]
