# Generated by Django 5.2.5 on 2026-02-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_system_fee_alter_order_tailor_status'),
    ]

    operations = [
        # Index for general analytics queries filtered by status and date
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='order_status_created_idx'),
        ),
        # Index for tailor-specific analytics
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tailor', 'status', 'created_at'], name='order_tailor_status_idx'),
        ),
        # Index for rider-specific analytics
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['rider', 'status', 'created_at'], name='order_rider_status_idx'),
        ),
        # Index for customer analytics
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'created_at'], name='order_customer_created_idx'),
        ),
        # Index for payment method analytics
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'created_at'], name='order_payment_created_idx'),
        ),
    ]
