# Generated by Django 5.2.5 on 2026-02-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_analytics_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_tailor_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_rider_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_customer_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_payment_created_idx',
        ),
    ]
