# Generated by Django 5.2.5 on 2026-04-27 11:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_tailor_rating_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='express_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra fee for express delivery', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='is_express',
            field=models.BooleanField(default=False, help_text='Whether this order uses express delivery (extra fast stitching)'),
        ),
    ]
