# Generated by Django 5.2.5 on 2026-05-18 10:35

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_order_express_fee_order_is_express'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.UUIDField(blank=True, help_text='Unique key from frontend to prevent duplicate order creation', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rider_status',
            field=django_fsm.FSMField(choices=[('none', 'Not Assigned'), ('accepted', 'Accepted Order'), ('on_way_to_pickup', 'On Way to Pickup'), ('picked_up', 'Picked Up'), ('on_way_to_delivery', 'On Way to Delivery'), ('on_way_to_measurement', 'On Way to Measurement'), ('measuring', 'Measuring'), ('measurement_taken', 'Measurement Taken'), ('delivered', 'Delivered')], db_index=True, default='none', help_text='Current rider activity status', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('ready_for_delivery', 'Ready for Delivery'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Delivered'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Main status of the order', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tailor_status',
            field=django_fsm.FSMField(choices=[('none', 'New'), ('accepted', 'Accepted Order'), ('in_progress', 'In Progress'), ('stitching_started', 'Started Stitching'), ('stitched', 'Finished Stitching'), ('measurements_complete', 'Measurements Complete'), ('record_measurements', 'Record Measurements')], db_index=True, default='none', help_text='Current tailor activity status', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
