# Generated by Django 5.2.5 on 2026-05-26 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_idempotency_key_alter_order_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='External payment gateway reference for paid online orders', max_length=150, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_unique_key', models.CharField(db_index=True, help_text='Public checkout key sent to the payment gateway/frontend', max_length=40, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('order_created', 'Order Created'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment Failed')], db_index=True, default='active', max_length=20)),
                ('request_payload', models.JSONField(help_text='Original order creation payload from the mobile app')),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict, help_text='Backend-calculated totals shown on checkout')),
                ('client_idempotency_key', models.CharField(blank=True, db_index=True, help_text='Optional frontend retry key for checkout creation', max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer')], max_length=20, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Gateway transaction/reference supplied after frontend payment', max_length=150, null=True, unique=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer who owns this checkout draft', on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, help_text='Order created from this checkout session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_session', to='orders.order')),
            ],
            options={
                'verbose_name': 'Checkout Session',
                'verbose_name_plural': 'Checkout Sessions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_idempotency_key__isnull', False)), fields=('customer', 'client_idempotency_key'), name='unique_customer_checkout_idempotency_key')],
            },
        ),
    ]
