# Generated by Django 5.2.5 on 2026-06-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_add_stitching_only_order_type'),
        ('orders', '0032_checkoutsession_payment_initiated_status'),
    ]

    operations = [
    ]
