# Generated by Django 5.2.5 on 2026-06-24 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_order_measurement_delivery_riders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainingPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_unique_key', models.CharField(db_index=True, help_text='Public remaining-balance payment key sent to the payment gateway/frontend', max_length=40, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment Failed')], db_index=True, default='active', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('payment_reference', models.CharField(blank=True, help_text='Gateway transaction/reference supplied after verified payment', max_length=150, null=True, unique=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer who owns this payment session', on_delete=django.db.models.deletion.CASCADE, related_name='remaining_payment_sessions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order whose remaining balance is being paid', on_delete=django.db.models.deletion.CASCADE, related_name='remaining_payment_sessions', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='orders_rema_order_i_ae68f7_idx'), models.Index(fields=['customer', 'status'], name='orders_rema_custome_3345b7_idx')],
            },
        ),
    ]
