# Generated by Django 5.2.5 on 2026-08-20 09:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_orderitem_recipient_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer_fabric_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meters of customer-provided fabric for stitching-only orders', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='CustomerFabricImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Photo of fabric brought by the customer', upload_to='customer_fabrics/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Display order of this photo on the order item')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(blank=True, help_text='Set when this photo is attached to a stitching-only order item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_fabric_images', to='orders.orderitem')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_fabric_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Fabric Image',
                'verbose_name_plural': 'Customer Fabric Images',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['uploaded_by', 'created_at'], name='orders_cust_upload__idx'), models.Index(fields=['order_item', 'display_order'], name='orders_cust_item_ord_idx')],
            },
        ),
    ]
