# Generated by Django 5.2.6 on 2025-10-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_tag',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('work', 'Work'), ('other', 'Other')], default='home', help_text='Address type: home, office, work, other', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='formatted_address',
            field=models.TextField(blank=True, help_text='Full formatted address from Google Maps API', null=True),
        ),
    ]
