# Generated by Django 4.2.23 on 2025-09-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='loyality_points',
        ),
    ]
