# Generated by Django 5.2.6 on 2025-10-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_address_address_tag_address_formatted_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='extra_info',
            field=models.TextField(blank=True, help_text='Additional address information', null=True),
        ),
    ]
