# Generated by Django 5.2.6 on 2025-12-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_add_extra_info_to_address'),
        ('tailors', '0003_fabric_stitching_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the fabric was favorited')),
                ('fabric', models.ForeignKey(help_text='Fabric that was favorited', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='tailors.fabric')),
                ('user', models.ForeignKey(help_text='User who favorited this fabric', on_delete=django.db.models.deletion.CASCADE, related_name='fabric_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fabric Favorite',
                'verbose_name_plural': 'Fabric Favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='customers_f_user_id_cd74ee_idx'), models.Index(fields=['fabric', 'created_at'], name='customers_f_fabric__ec8b1d_idx')],
                'unique_together': {('user', 'fabric')},
            },
        ),
    ]
