# Generated by Django 5.2.5 on 2025-12-11 13:36

from django.db import migrations, models


def migrate_formatted_address_to_address(apps, schema_editor):
    """Migrate data from formatted_address to address field."""
    Address = apps.get_model('customers', 'Address')
    for addr in Address.objects.all():
        if addr.formatted_address and not addr.address:
            addr.address = addr.formatted_address
            addr.save(update_fields=['address'])


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_fabricfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, help_text='Full address text', null=True),
        ),
        migrations.RunPython(migrate_formatted_address_to_address, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='address',
            name='formatted_address',
        ),
    ]
