# Generated by Django 5.2.5 on 2025-09-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_address_unique_default_address_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_default_address_per_user',
        ),
    ]
