# Generated by Django 5.2.5 on 2025-12-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_add_address_remove_formatted_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='measurements',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
