# Generated by Django 5.2.5 on 2026-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customerprofile_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='first_free_measurement_used',
            field=models.BooleanField(default=False, help_text='Whether customer account has used the one-time free measurement service'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='free_measurement_date',
            field=models.DateTimeField(blank=True, help_text='When the free measurement order was completed', null=True),
        ),
    ]
