# Generated by Django 5.2.5 on 2026-02-23 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_add_free_measurement_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='pos_created_by',
            field=models.ForeignKey(blank=True, help_text='Tailor who created this customer via the POS system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_created_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
