# Generated by Django 5.2.5 on 2026-08-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_pos_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='welcome_sms_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the onboarding welcome SMS was sent to this customer', null=True),
        ),
    ]
