# Generated by Django 5.2.5 on 2025-09-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_rename_customer_profile_familymember_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='loyalty_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
