# Generated by Django 5.2.5 on 2026-08-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_pos_family_member_provenance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerdataauditlog',
            new_name='customers_c_custome_d6c96b_idx',
            old_name='customers_c_custome_0a8f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='customerdataauditlog',
            new_name='customers_c_entity__19f635_idx',
            old_name='customers_c_entity__b8e0f1_idx',
        ),
    ]
