# Generated by Django 5.2.5

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_audit_log_rider_app_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailorPOSCustomerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(
                    help_text='Customer account added via POS',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='pos_tailor_links',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('tailor', models.ForeignKey(
                    help_text='Shop owner who added this customer via POS',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='pos_customer_links',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),
        migrations.AddIndex(
            model_name='tailorposcustomerlink',
            index=models.Index(fields=['tailor', 'customer'], name='customers_t_tailor__idx'),
        ),
        migrations.AddConstraint(
            model_name='tailorposcustomerlink',
            constraint=models.UniqueConstraint(
                fields=('customer', 'tailor'),
                name='uniq_pos_customer_tailor_link',
            ),
        ),
    ]
