# Generated by Django 5.2.5 on 2026-09-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_tailor_pos_customer_link'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tailorposcustomerlink',
            new_name='customers_t_tailor__320f30_idx',
            old_name='customers_t_tailor__idx',
        ),
    ]
