# Generated by Django 4.2.23 on 2025-09-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vehicle_info',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('RIDER', 'Rider'), ('TAILOR', 'Tailor'), ('ADMIN', 'Admin')], default='USER', max_length=10),
        ),
    ]
