# Generated by Django 5.2.4 on 2025-08-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
