# Generated by Django 5.2.6 on 2025-12-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phone_unique_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth", null=True),
        ),
    ]
