# Generated by Django 5.2.4 on 2025-08-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text="Working hours stored as JSON. Format: {'monday': {'is_open': true, 'start_time': '09:00', 'end_time': '18:00'}}", null=True),
        ),
    ]
