# Generated by Django 5.2.5 on 2026-03-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='ar', max_length=2),
        ),
    ]
