# Generated by Django 5.2.5 on 2026-07-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('ur', 'Urdu')], default='ar', max_length=2),
        ),
    ]
