# Generated by Django 5.2.5 on 2026-08-03 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('push', 'Push notification'), ('both', 'SMS and push')], default='sms', max_length=10)),
                ('audience_type', models.CharField(choices=[('single', 'Single user'), ('role', 'All users with role'), ('selected', 'Selected users')], default='single', max_length=10)),
                ('target_role', models.CharField(blank=True, choices=[('USER', 'Customer'), ('TAILOR', 'Tailor'), ('RIDER', 'Rider')], max_length=10, null=True)),
                ('title', models.CharField(blank=True, help_text='Required for push notifications', max_length=255)),
                ('body', models.TextField(help_text='Message text (SMS body and/or push body)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, related_name='admin_outbound_message_batches', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_outbound_messages', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_messages_received_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin message',
                'verbose_name_plural': 'Messaging center',
                'ordering': ['-created_at'],
                'permissions': [('send_admin_message', 'Can send admin messages')],
            },
        ),
        migrations.CreateModel(
            name='AdminMessageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_used', models.CharField(blank=True, max_length=20)),
                ('sms_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('push_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('partial', 'Partially sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_message_deliveries', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='messaging.adminoutboundmessage')),
            ],
            options={
                'verbose_name': 'Message delivery',
                'verbose_name_plural': 'Message deliveries',
                'ordering': ['-created_at'],
                'unique_together': {('message', 'user')},
            },
        ),
    ]
