# Generated by Django 5.2.5 on 2026-09-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0001_move_v2_fabrics_to_fabrics_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricproduct',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fabricproduct',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabricproduct',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabricproduct',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fabricproduct',
            name='sale_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
