# Generated by Django 5.2.5 on 2026-09-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0002_fabric_product_sale_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricproduct',
            name='default_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
