# Generated by Django 5.2.5 on 2026-09-28 14:38

from django.db import migrations, models


def backfill_shop_origin_catalog_visibility(apps, schema_editor):
    FabricProduct = apps.get_model('fabrics', 'FabricProduct')
    ShopFabric = apps.get_model('fabrics', 'ShopFabric')
    Fabric = apps.get_model('tailors', 'Fabric')

    for product in FabricProduct.objects.all().iterator():
        shop_fabrics = ShopFabric.objects.filter(
            product_id=product.id,
            legacy_fabric_id__isnull=False,
        )
        for shop_fabric in shop_fabrics.iterator():
            legacy = Fabric.objects.filter(pk=shop_fabric.legacy_fabric_id).first()
            if legacy and legacy.created_at < product.created_at:
                FabricProduct.objects.filter(pk=product.pk).update(show_in_owner_catalog=False)
                break


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0003_fabricproduct_default_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricproduct',
            name='show_in_owner_catalog',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunPython(
            backfill_shop_origin_catalog_visibility,
            migrations.RunPython.noop,
        ),
    ]
