"""
Django settings for zthob project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import List
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    print("file not found")
    # python-dotenv not installed, skip .env loading
    pass

# Environment Detection
# APP_ENV can be: development, staging, production
APP_ENV = os.getenv('APP_ENV', 'development')
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-vv#!hz_y7dae4soqei&61+5l-5@(cr@kaz#($@5-nyb5jsku1=')

# SECURITY WARNING: don't run with debug turned on in production!
if APP_ENV == 'production':
    DEBUG = False
elif APP_ENV == 'staging':
    # Allow debug in staging for easier troubleshooting
    DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# ALLOWED_HOSTS configuration - ensure production IP is always included
default_hosts = ['localhost', '127.0.0.1', '0.0.0.0', '69.62.126.95', 'mgask.net', 'www.mgask.net', 'app.mgask.net', 'prod.mgask.net']
env_hosts = os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')
# Filter out empty strings from split
env_hosts = [h.strip() for h in env_hosts if h.strip()]
# Merge environment hosts with defaults, ensuring no duplicates
ALLOWED_HOSTS = list(set(env_hosts + default_hosts)) if env_hosts else default_hosts
# Application definition

INSTALLED_APPS = [
  # Must be before django.contrib.admin
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third Pary Packages
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_spectacular",
    # Apps
    "apps.core",
    "apps.accounts",
    "apps.tailors",
    "apps.customers",
    "apps.orders",
    "apps.riders",
    "apps.notifications",
    "apps.deliveries",
    "apps.customization",
]
    
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "zthob.middleware.TranslationMiddleware",  # For automatic API response translation
]

ROOT_URLCONF = "zthob.urls"
AUTH_USER_MODEL="accounts.CustomUser"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "zthob.wsgi.application"


# Database Configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
if APP_ENV == 'production':
    # Production: Use PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'mgask'),
            'USER': os.getenv('DB_USER', 'mgask_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': 600,  # Connection pooling
        }
    }
elif APP_ENV == 'staging':
    # Staging: Use PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'mgask_staging'),
            'USER': os.getenv('DB_USER', 'mgask_staging_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': 600,  # Connection pooling
        }
    }
else:
    # Development: Use SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Currency settings for Saudi Arabia
CURRENCY_CODE = 'SAR'  # Saudi Riyal
CURRENCY_SYMBOL = 'SAR'  # Display as 'SAR' instead of 'ر.س'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files
# MEDIA_URL = "/media/"
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Security Settings
if APP_ENV in ['production', 'staging']:
    # HTTPS settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Other security settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_FRAME_DENY = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Session security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    
    # CSRF trusted origins for HTTPS
    CSRF_TRUSTED_ORIGINS = [
        'https://69.62.126.95',
        'https://mgask.net',
        'https://www.mgask.net',
        'https://app.mgask.net',
        'https://prod.mgask.net',
    ]

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Email settings (for production and staging)
if APP_ENV in ['production', 'staging']:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@zthob.com')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    'EXCEPTION_HANDLER': 'zthob.utils.custom_exception_handler',
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME" : timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME" : timedelta(days=14),
    "ROTATE_REFRESH_TOKENS" : True,
    "BLACKLIST_AFTER_ROTATION": True, 
}

CORS_ALLOWED_ORIGINS=[
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://69.62.126.95",
    "https://mgask.net",
    "https://www.mgask.net",
    "https://app.mgask.net",
    "https://prod.mgask.net",
]

CORS_ALLOW_CREDENTIALS=True

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Zthob API',
    'DESCRIPTION': 'Zthob API documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [{
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }],
}

# Firebase Configuration
# Service Account JSON file path (required for Firebase Admin SDK)
# Set FIREBASE_CREDENTIALS_PATH in .env to point to your service account JSON file
# Supports both absolute paths and relative paths (relative to BASE_DIR)
_firebase_cred_path = os.getenv('FIREBASE_CREDENTIALS_PATH', None)
if _firebase_cred_path:
    # If path is relative, make it absolute relative to BASE_DIR
    if not os.path.isabs(_firebase_cred_path):
        _firebase_cred_path = str(BASE_DIR / _firebase_cred_path)
    # Convert to absolute path to ensure it works regardless of working directory
    _firebase_cred_path = os.path.abspath(_firebase_cred_path)
FIREBASE_CREDENTIALS_PATH = _firebase_cred_path

# Firebase Project ID
FIREBASE_PROJECT_ID = os.getenv('FIREBASE_PROJECT_ID', 'mgask-2025')

# Twilio SMS Configuration
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', None)
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', None)
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', None)
TWILIO_VERIFY_SERVICE_SID = os.getenv('TWILIO_VERIFY_SERVICE_SID', None)

# Jazzmin Admin UI Configuration - Simplified
JAZZMIN_SETTINGS = {
    # Simple branding
    "site_title": "Mgask Admin",
    "site_header": "Mgask",
    "site_brand": "Mgask",
    "welcome_sign": "Welcome to Mgask",
    "copyright": "Mgask Team",

    # Simplified search - only search users
    "search_model": "accounts.CustomUser",

    # Clean top menu - only essential links
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index"},
        {"name": "Users", "model": "accounts.CustomUser"},
    ],

    # Simple user menu
    "usermenu_links": [
        {"model": "accounts.CustomUser"}
    ],

    # Simplified sidebar
    "show_sidebar": True,
    "navigation_expanded": False,  # Start collapsed for cleaner look
    "hide_apps": ["auth"],  # Hide Django's default auth app
    "hide_models": ["auth.Group"],  # Hide groups

    # Organized menu order - most important first
    "order_with_respect_to": ["accounts", "customers", "tailors", "orders", "core"],

    # Simple, clear icons - comprehensive icon set for all models
    "icons": {
        # Auth (hidden but icon needed for completeness)
        "auth.Group": "fas fa-users-cog",
        
        # Accounts
        "accounts.CustomUser": "fas fa-users",
        
        # Customers
        "customers.CustomerProfile": "fas fa-user",
        "customers.Address": "fas fa-map-marker-alt",
        "customers.FamilyMember": "fas fa-user-friends",
        
        # Tailors
        "tailors.TailorProfile": "fas fa-cut",
        "tailors.Fabric": "fas fa-tshirt",
        "tailors.FabricCategory": "fas fa-tags",
        "tailors.FabricType": "fas fa-layer-group",
        "tailors.FabricTag": "fas fa-tag",
        "tailors.FabricImage": "fas fa-image",
        "tailors.TailorProfileReview": "fas fa-clipboard-check",
        "tailors.ServiceArea": "fas fa-map-marked-alt",
        
        # Orders
        "orders.Order": "fas fa-shopping-cart",
        "orders.OrderItem": "fas fa-shopping-bag",
        "orders.OrderStatusHistory": "fas fa-history",
        
        # Riders
        "riders.RiderProfile": "fas fa-motorcycle",
        "riders.RiderOrderAssignment": "fas fa-route",
        "riders.RiderProfileReview": "fas fa-user-check",
        "riders.RiderDocument": "fas fa-file-alt",
        
        # Notifications
        "notifications.FCMDeviceToken": "fas fa-mobile-alt",
        "notifications.NotificationLog": "fas fa-bell",
        
        # Deliveries
        "deliveries.DeliveryTracking": "fas fa-truck",
        "deliveries.LocationHistory": "fas fa-map-marked-alt",
        
        # Core
        "core.SystemSettings": "fas fa-cog",
        "core.Slider": "fas fa-images",
        "core.PhoneVerification": "fas fa-phone-alt",
    },

    # Simplified forms - single column for easier use
    "changeform_format": "single",
    "changeform_format_overrides": {},

    # Clean UI
    "related_modal_active": False,
    "show_ui_builder": False,
    "language_chooser": False,
    "use_google_fonts_cdn": True,
    
    # Custom styling for simplicity
    "custom_css": ["admin/css/custom_admin.css", "admin/css/dashboard_widgets.css"],
    "custom_js": None,
}
