# Generated by Django 5.2.6 on 2025-10-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TailorServiceArea',
        ),
    ]
