# Generated by Django 4.2.23 on 2025-09-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailorprofile',
            name='establishment_year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tailorprofile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tailorprofile',
            name='tailor_experience',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
