# Generated by Django 5.2.6 on 2025-11-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0002_delete_tailorservicearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='stitching_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for stitching service', max_digits=10, null=True),
        ),
    ]
