# Generated by Django 4.2.23 on 2025-09-04 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tailors', '0002_alter_tailorprofile_establishment_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tailor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
