# Generated by Django 5.2.5 on 2026-02-22 07:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_tailor_rating_model'),
        ('tailors', '0003_fabric_stitching_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tailorprofile',
            name='avg_on_time_delivery',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average on-time delivery rating (cached from TailorRating)', max_digits=3),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='avg_overall_satisfaction',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average overall satisfaction rating (cached from TailorRating)', max_digits=3),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='avg_stitching_quality',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average stitching quality rating (cached from TailorRating)', max_digits=3),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of ratings received'),
        ),
        migrations.CreateModel(
            name='TailorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stitching_quality', models.PositiveSmallIntegerField(help_text='Stitching quality rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('on_time_delivery', models.PositiveSmallIntegerField(help_text='On-time delivery rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_satisfaction', models.PositiveSmallIntegerField(help_text='Overall satisfaction rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional written review by the customer', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='The customer who submitted this rating', on_delete=django.db.models.deletion.CASCADE, related_name='tailor_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='The completed order this rating is for (one rating per order)', on_delete=django.db.models.deletion.CASCADE, related_name='tailor_rating', to='orders.order')),
                ('tailor', models.ForeignKey(help_text='The tailor being rated', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tailors.tailorprofile')),
            ],
            options={
                'verbose_name': 'Tailor Rating',
                'verbose_name_plural': 'Tailor Ratings',
                'ordering': ['-created_at'],
            },
        ),
    ]
