# Generated by Django on 2026-03-30 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tailors', '0004_tailor_rating_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailorEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(default=list, help_text='List of roles assigned to this employee')),
                ('can_manage_orders', models.BooleanField(db_index=True, default=False)),
                ('can_manage_catalog', models.BooleanField(db_index=True, default=False)),
                ('can_view_analytics', models.BooleanField(db_index=True, default=False)),
                ('can_manage_employees', models.BooleanField(db_index=True, default=False)),
                ('can_manage_pos', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tailor', models.ForeignKey(help_text='The tailor shop this employee belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tailors.tailorprofile')),
                ('user', models.OneToOneField(help_text='The user account of this employee', on_delete=django.db.models.deletion.CASCADE, related_name='tailor_employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tailor Employee',
                'verbose_name_plural': 'Tailor Employees',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['tailor', 'is_active'], name='tailors_tai_tailor__245ee1_idx')],
            },
        ),
    ]
