# Generated by Django 5.2.5 on 2025-09-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0004_fabriccategory_alter_tailorprofile_working_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricimage',
            options={'ordering': ['-is_primary', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='fabricimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Designates this image as the primary image'),
        ),
        migrations.AddConstraint(
            model_name='fabricimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('fabric',), name='unique_primary_image'),
        ),
    ]
