# Generated by Django 5.2.5 on 2026-04-18 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0005_tailoremployee'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tailoremployee',
            new_name='tailors_tai_tailor__21b658_idx',
            old_name='tailors_tai_tailor__245ee1_idx',
        ),
        migrations.AddField(
            model_name='fabric',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sale price if is_on_sale is True', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this fabric should be featured on the home page'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Whether this fabric is currently on flash sale'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this fabric has been ordered'),
        ),
        migrations.AddField(
            model_name='fabriccategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Category icon/image for display on home page', null=True, upload_to='categories/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this tailor should be featured on the home page'),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this tailor is verified by the platform'),
        ),
    ]
