# Generated by Django 5.2.5 on 2025-09-12 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0005_alter_fabricimage_options_fabricimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='fabric_image',
            field=models.ImageField(blank=True, null=True, upload_to='fabrics/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
