# Generated by Django 5.2.5 on 2026-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0006_rename_tailors_tai_tailor__245ee1_idx_tailors_tai_tailor__21b658_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='sale_end',
            field=models.DateTimeField(blank=True, help_text='When the flash sale ends', null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='sale_start',
            field=models.DateTimeField(blank=True, help_text='When the flash sale begins', null=True),
        ),
    ]
