# Generated by Django 5.2.6 on 2025-10-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0007_alter_fabric_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='seasons',
            field=models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('all_season', 'All Season')], default='all_season', help_text='Best suited season for this fabric', max_length=20),
        ),
    ]
