# Generated by Django 5.2.5 on 2026-04-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0007_fabric_sale_end_fabric_sale_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailorprofile',
            name='express_delivery_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days for express delivery (e.g. 4 days)', null=True),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='express_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Extra fee for express delivery', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='is_express_delivery_enabled',
            field=models.BooleanField(default=False, help_text='Whether this tailor provides express delivery (extra fast stitching)'),
        ),
    ]
