# Generated by Django 5.2.5 on 2026-05-08 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0008_tailorprofile_express_delivery_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status from admin', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['is_featured'], name='tailors_fab_is_feat_3b0940_idx'),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['approval_status'], name='tailors_fab_approva_e7d9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['is_on_sale', 'sale_start', 'sale_end'], name='tailors_fab_is_on_s_38a3ab_idx'),
        ),
    ]
