# Generated by Django 5.2.5 on 2026-06-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0009_fabric_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tailorrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
