# Generated by Django 5.2.6 on 2025-10-10 06:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0009_fabrictype_fabric_fabric_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabric',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fabric', 'verbose_name_plural': 'Fabrics'},
        ),
        migrations.AlterModelOptions(
            name='fabriccategory',
            options={'ordering': ['name'], 'verbose_name': 'Fabric Category', 'verbose_name_plural': 'Fabric Categories'},
        ),
        migrations.AlterModelOptions(
            name='fabricimage',
            options={'ordering': ['-is_primary', 'order', 'id'], 'verbose_name': 'Fabric Image', 'verbose_name_plural': 'Fabric Images'},
        ),
        migrations.AlterModelOptions(
            name='fabrictype',
            options={'ordering': ['name'], 'verbose_name': 'Fabric Type', 'verbose_name_plural': 'Fabric Types'},
        ),
        migrations.AlterModelOptions(
            name='tailorprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tailor Profile', 'verbose_name_plural': 'Tailor Profiles'},
        ),
        migrations.RemoveConstraint(
            model_name='fabricimage',
            name='unique_primary_image',
        ),
        migrations.AlterField(
            model_name='fabric',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of fabric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='tailors.fabriccategory'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the fabric', null=True),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fabric_image',
            field=models.ImageField(blank=True, help_text='Legacy single image field - use gallery instead', null=True, upload_to='fabrics/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fabric_type',
            field=models.ForeignKey(blank=True, help_text='Type of fabric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='tailors.fabrictype'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this fabric is available for sale'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='name',
            field=models.CharField(help_text='Name of the fabric', max_length=100),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='sku',
            field=models.CharField(editable=False, help_text='Stock Keeping Unit - auto-generated', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='stock',
            field=models.PositiveIntegerField(default=1, help_text='Available stock quantity'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='tailor',
            field=models.ForeignKey(help_text='Tailor who owns this fabric', on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='tailors.tailorprofile'),
        ),
        migrations.AlterField(
            model_name='fabriccategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this category is active'),
        ),
        migrations.AlterField(
            model_name='fabriccategory',
            name='name',
            field=models.CharField(help_text='Name of the fabric category', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fabricimage',
            name='fabric',
            field=models.ForeignKey(help_text='Fabric this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tailors.fabric'),
        ),
        migrations.AlterField(
            model_name='fabricimage',
            name='image',
            field=models.ImageField(help_text='Image file', upload_to='fabrics/gallery', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='fabricimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order of the image'),
        ),
        migrations.AlterField(
            model_name='fabrictype',
            name='name',
            field=models.CharField(help_text='Name of the fabric type (e.g., Cotton, Silk, Wool)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tailorprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Business address', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tailorprofile',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Primary contact number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tailorprofile',
            name='establishment_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the business was established', null=True),
        ),
        migrations.AlterField(
            model_name='tailorprofile',
            name='shop_name',
            field=models.CharField(blank=True, help_text="Name of the tailor's shop", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tailorprofile',
            name='shop_status',
            field=models.BooleanField(default=True, help_text='Whether the shop is currently open'),
        ),
        migrations.AlterField(
            model_name='tailorprofile',
            name='tailor_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of tailoring experience', null=True),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['tailor', 'is_active'], name='tailors_fab_tailor__d08b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['fabric_type', 'seasons'], name='tailors_fab_fabric__d3a95b_idx'),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['category', 'is_active'], name='tailors_fab_categor_73b49f_idx'),
        ),
        migrations.AddConstraint(
            model_name='fabricimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('fabric',), name='unique_primary_image_per_fabric'),
        ),
    ]
