# Generated by Django 5.2.6 on 2025-10-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0010_alter_fabric_options_alter_fabriccategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fabric Tag',
                'verbose_name_plural': 'Fabric Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fabric',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this fabric', related_name='fabrics', to='tailors.fabrictag'),
        ),
    ]
