# Generated by Django 5.2.5 on 2026-06-09 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_fabric_countries(apps, schema_editor):
    FabricCountry = apps.get_model('tailors', 'FabricCountry')

    countries = [
        {
            "code": "JP",
            "name": "Japan",
            "name_ar": "اليابان",
            "description_ar": "معروفة بالأقمشة الفاخرة مثل توبيو وسيجاي",
            "famous_mills": "Shikibo, Teijin",
            "display_order": 1,
            "is_active": True,
        },
        {
            "code": "KR",
            "name": "South Korea",
            "name_ar": "كوريا الجنوبية",
            "description_ar": "تشتهر بأقمشة الهيلانة والأقمشة المقاومة للتجعد",
            "display_order": 2,
            "is_active": True,
        },
        {
            "code": "CN",
            "name": "China",
            "name_ar": "الصين",
            "description_ar": "أكبر منتج عالمي للأقمشة بمختلف الفئات السعرية",
            "display_order": 3,
            "is_active": True,
        },
        {
            "code": "IN",
            "name": "India",
            "name_ar": "الهند",
            "description_ar": "قوية في القطن والأقمشة المخلوطة",
            "display_order": 4,
            "is_active": True,
        },
        {
            "code": "ID",
            "name": "Indonesia",
            "name_ar": "إندونيسيا",
            "description_ar": "تستخدم أقمشتها كثيراً في الثياب الاقتصادية والمتوسطة",
            "display_order": 5,
            "is_active": True,
        },
        {
            "code": "TH",
            "name": "Thailand",
            "name_ar": "تايلاند",
            "description_ar": "تنتج أقمشة بوليستر وخلطات مناسبة للثياب",
            "display_order": 6,
            "is_active": True,
        },
        {
            "code": "IT",
            "name": "Italy",
            "name_ar": "إيطاليا",
            "description_ar": "للأقمشة الفاخرة جداً والماركات الراقية",
            "display_order": 7,
            "is_active": True,
        },
        {
            "code": "UK",
            "name": "United Kingdom",
            "name_ar": "المملكة المتحدة",
            "description_ar": "معروفة بالأقمشة الكلاسيكية الراقية",
            "display_order": 8,
            "is_active": True,
        },
    ]

    for country in countries:
        FabricCountry.objects.update_or_create(
            code=country["code"],
            defaults=country,
        )


def unseed_fabric_countries(apps, schema_editor):
    FabricCountry = apps.get_model('tailors', 'FabricCountry')
    FabricCountry.objects.filter(code__in=["JP", "KR", "CN", "IN", "ID", "TH", "IT", "UK"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0010_alter_fabric_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short country code like JP, KR, CN', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Country name in English', max_length=100, unique=True)),
                ('name_ar', models.CharField(blank=True, help_text='Country name in Arabic', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Short description in English', null=True)),
                ('description_ar', models.TextField(blank=True, help_text='Short description in Arabic', null=True)),
                ('famous_mills', models.TextField(blank=True, help_text='Comma-separated famous mills or manufacturers', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls display order in dropdowns')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this country is available for selection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fabric Country',
                'verbose_name_plural': 'Fabric Countries',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='fabric',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country selected for this fabric', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='tailors.fabriccountry'),
        ),
        migrations.AddIndex(
            model_name='fabriccountry',
            index=models.Index(fields=['is_active', 'display_order'], name='tailors_fab_is_acti_da5539_idx'),
        ),
        migrations.RunPython(seed_fabric_countries, unseed_fabric_countries),
    ]
