# Generated by Django 5.2.6 on 2025-10-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0011_fabrictag_fabric_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabrictag',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
