# Generated by Django 5.2.5 on 2025-10-10 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0012_alter_fabrictag_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailorProfileReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Review status of the tailor profile', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the profile was submitted for review', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the profile was reviewed by admin', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('service_areas', models.JSONField(blank=True, default=list, help_text='List of cities/areas served by this tailor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='tailors.tailorprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tailor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tailor Profile Review',
                'verbose_name_plural': 'Tailor Profile Reviews',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
