# Generated by Django 5.2.5 on 2025-10-10 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0013_tailorprofilereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tailorprofilereview',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Profile Review', 'verbose_name_plural': 'Profile Reviews'},
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service area (e.g., Riyadh, Jeddah, Dammam)', max_length=100, unique=True)),
                ('city', models.CharField(help_text='City this service area belongs to', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service area is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='tailors_ser_city_c868a5_idx'), models.Index(fields=['is_active'], name='tailors_ser_is_acti_4ac6ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='TailorServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text="Whether this is the tailor's primary service area")),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Delivery fee for this area (optional)', max_digits=10, null=True)),
                ('estimated_delivery_days', models.PositiveIntegerField(blank=True, help_text='Estimated delivery time in days (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_area', models.ForeignKey(help_text='Service area being served', on_delete=django.db.models.deletion.CASCADE, related_name='tailors', to='tailors.servicearea')),
                ('tailor', models.ForeignKey(help_text='Tailor who serves this area', on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='tailors.tailorprofile')),
            ],
            options={
                'verbose_name': 'Tailor Service Area',
                'verbose_name_plural': 'Tailor Service Areas',
                'ordering': ['-is_primary', 'service_area__city', 'service_area__name'],
                'unique_together': {('tailor', 'service_area')},
            },
        ),
    ]
