# Generated by Django 5.2.5 on 2025-10-10 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0014_alter_tailorprofilereview_options_servicearea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailorprofile',
            name='shop_image',
            field=models.ImageField(blank=True, help_text='Shop image (JPG, JPEG, PNG only)', null=True, upload_to='tailor_profiles/shop_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
