# Generated by Django 5.2.5 on 2026-09-09 07:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0020_business_tailorprofile_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(editable=False, max_length=24, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stitching_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seasons', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('all_season', 'All Season')], default='all_season', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_products', to='tailors.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_products', to='tailors.fabriccategory')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_products', to='tailors.fabriccountry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fabric_products', to=settings.AUTH_USER_MODEL)),
                ('fabric_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_products', to='tailors.fabrictype')),
                ('tags', models.ManyToManyField(blank=True, related_name='v2_products', to='tailors.fabrictag')),
            ],
            options={
                'verbose_name': 'Fabric Product',
                'verbose_name_plural': 'Fabric Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FabricProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fabrics/v2/products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tailors.fabricproduct')),
            ],
            options={
                'ordering': ['-is_primary', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShopFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('reserved_stock', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('legacy_fabric', models.OneToOneField(blank=True, help_text='Legacy fabric row used by v1 order/checkout APIs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_shop_fabric', to='tailors.fabric')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_assignments', to='tailors.fabricproduct')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_fabrics', to='tailors.tailorprofile')),
            ],
            options={
                'verbose_name': 'Shop Fabric',
                'verbose_name_plural': 'Shop Fabrics',
            },
        ),
        migrations.CreateModel(
            name='FabricStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('adjustment_add', 'Adjustment add'), ('adjustment_remove', 'Adjustment remove'), ('adjustment_set', 'Adjustment set'), ('assign', 'Assign')], max_length=32)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.PositiveIntegerField()),
                ('new_stock', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('order_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('shop_fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='tailors.shopfabric')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fabricproduct',
            index=models.Index(fields=['business', 'is_active'], name='tailors_fab_busines_7977f6_idx'),
        ),
        migrations.AddIndex(
            model_name='fabricproduct',
            index=models.Index(fields=['business', 'approval_status'], name='tailors_fab_busines_6a90d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='fabricproductimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='uniq_v2_primary_image_per_product'),
        ),
        migrations.AddIndex(
            model_name='shopfabric',
            index=models.Index(fields=['shop', 'is_active', 'is_visible'], name='tailors_sho_shop_id_7766f3_idx'),
        ),
        migrations.AddIndex(
            model_name='shopfabric',
            index=models.Index(fields=['product', 'is_active'], name='tailors_sho_product_ea359b_idx'),
        ),
        migrations.AddConstraint(
            model_name='shopfabric',
            constraint=models.UniqueConstraint(fields=('shop', 'product'), name='uniq_shop_fabric_product'),
        ),
        migrations.AddIndex(
            model_name='fabricstockmovement',
            index=models.Index(fields=['shop_fabric', 'movement_type', 'created_at'], name='tailors_fab_shop_fa_7724e2_idx'),
        ),
    ]
