# Generated by Django 5.2.5 on 2026-09-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0021_v2_fabric_catalog'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='shopfabric',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='fabricproductimage',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='fabricstockmovement',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='fabricstockmovement',
                    name='shop_fabric',
                ),
                migrations.RemoveField(
                    model_name='shopfabric',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='shopfabric',
                    name='legacy_fabric',
                ),
                migrations.RemoveField(
                    model_name='shopfabric',
                    name='shop',
                ),
                migrations.DeleteModel(
                    name='FabricProduct',
                ),
                migrations.DeleteModel(
                    name='FabricProductImage',
                ),
                migrations.DeleteModel(
                    name='FabricStockMovement',
                ),
                migrations.DeleteModel(
                    name='ShopFabric',
                ),
            ],
        ),
    ]
