# Generated by Django 5.2.6 on 2025-11-12 19:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), help_text='Tax/VAT rate as decimal (e.g., 0.15 for 15%)', max_digits=5)),
                ('delivery_fee_under_10km', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Delivery fee for distances less than 10 KM (SAR)', max_digits=10)),
                ('delivery_fee_10km_and_above', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Delivery fee for distances 10 KM and above (SAR)', max_digits=10)),
                ('distance_threshold_km', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Distance threshold in KM for different delivery fees', max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Order subtotal threshold for free delivery (SAR). Set to 0 to disable free delivery.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether these settings are currently active')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about these settings', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who last updated these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
