# Generated by Django 5.2.6 on 2025-11-13 11:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title/Heading text to display on the slider', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description text to display on the slider (optional)', null=True)),
                ('image', models.ImageField(help_text='Slider image (JPG, JPEG, PNG only)', upload_to='sliders/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('button_text', models.CharField(blank=True, help_text='Text to display on the button (optional)', max_length=100, null=True)),
                ('button_link', models.CharField(blank=True, help_text='Link/URL to navigate when button is clicked (optional)', max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slider is currently active and should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this slider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sliders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
