# Generated by Django 5.2.6 on 2025-12-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='verification_sid',
            field=models.CharField(blank=True, help_text='Twilio Verify verification SID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='otp_code',
            field=models.CharField(blank=True, help_text='OTP code (for manual OTP) or empty if using Twilio Verify', max_length=6, null=True),
        ),
    ]
