# Generated by Django 5.2.5 on 2026-02-14 04:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_verification_sid_to_phone_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='system_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Fixed system fee (SAR) applied to fabric_with_stitching orders (non-walk-in).', max_digits=10),
        ),
    ]
