# Generated by Django 5.2.5 on 2026-04-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_system_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='express_delivery_max_days',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of days an admin allows for express delivery options (default: 10).'),
        ),
    ]
