# Generated by Django 5.2.5 on 2026-07-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mobileappversionpolicy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mobileappversionpolicy',
            new_name='core_mobile_app_8f1e46_idx',
            old_name='core_mobile_app_plat_6d0f8d_idx',
        ),
    ]
