# Generated by Django 5.2.5 on 2026-07-26

from django.db import migrations, models


def shorten_existing_otp_codes(apps, schema_editor):
    PhoneVerification = apps.get_model('core', 'PhoneVerification')
    PhoneVerification.objects.filter(otp_code='123456').update(otp_code='1234')
    for row in PhoneVerification.objects.exclude(otp_code__isnull=True).iterator():
        if len(row.otp_code) > 4:
            PhoneVerification.objects.filter(pk=row.pk).update(
                otp_code=row.otp_code[:4]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_systemsettings_express_delivery_options'),
    ]

    operations = [
        migrations.RunPython(shorten_existing_otp_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='phoneverification',
            name='otp_code',
            field=models.CharField(
                blank=True,
                help_text='OTP code (test phones) or empty if using Taqnyat Verify',
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='verification_sid',
            field=models.CharField(
                blank=True,
                help_text='Taqnyat Verify requestId',
                max_length=100,
                null=True,
            ),
        ),
    ]
