# Generated by Django 5.2.5 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_systemsettings_express_delivery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='otp_code',
            field=models.CharField(
                blank=True,
                help_text='OTP code (test phones) or empty if using Taqnyat Verify',
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='verification_sid',
            field=models.CharField(
                blank=True,
                help_text='Taqnyat Verify requestId',
                max_length=100,
                null=True,
            ),
        ),
    ]
