# Generated by Django 5.2.5 on 2025-12-30 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Internal name (e.g., 'collar', 'cuff', 'placket')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Display name shown to users (e.g., 'Collar Styles', 'Cuff Styles')", max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display categories (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is available for selection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Style Category',
                'verbose_name_plural': 'Custom Style Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Style name (e.g., 'Standard', 'Mandarin', 'Modern')", max_length=100)),
                ('code', models.CharField(help_text="Unique code for this style (e.g., 'collar_1_Standard')", max_length=50)),
                ('image', models.ImageField(help_text='Style image (PNG/JPG)', upload_to='custom_styles/%Y/%m/')),
                ('description', models.TextField(blank=True, help_text='Optional description of this style', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display within category (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this style is available for selection')),
                ('extra_price', models.DecimalField(blank=True, decimal_places=2, help_text='Additional cost for this style (leave empty if no extra charge)', max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Category this style belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='customization.customstylecategory')),
            ],
            options={
                'verbose_name': 'Custom Style',
                'verbose_name_plural': 'Custom Styles',
                'ordering': ['category', 'display_order', 'name'],
                'unique_together': {('category', 'code')},
            },
        ),
    ]
