# Generated by Django 5.2.5 on 2025-12-31 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStylePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of this style preset', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of this style preset', null=True)),
                ('styles', models.JSONField(default=list, help_text="Selected styles. Format: [{'category': 'collar', 'style_id': 8}]")),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default style preset")),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this preset has been used')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User this preset belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='style_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Style Preset',
                'verbose_name_plural': 'User Style Presets',
                'ordering': ['-is_default', '-usage_count', '-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
