# Generated by Django 5.2.5 on 2026-02-12 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_userstylepreset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Internal name (e.g., 'thobe', 'pants')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='English display name', max_length=100)),
                ('display_name_ar', models.CharField(help_text='Arabic display name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('default_unit', models.CharField(choices=[('cm', 'Centimeters'), ('inches', 'Inches')], default='cm', help_text='Default unit for measurement fields', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display templates (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Measurement Template',
                'verbose_name_plural': 'Measurement Templates',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Internal key (e.g., 'chest', 'waist')", max_length=50)),
                ('display_name', models.CharField(help_text='English label', max_length=100)),
                ('display_name_ar', models.CharField(help_text='Arabic label', max_length=100)),
                ('field_type', models.CharField(choices=[('decimal', 'Decimal Number'), ('integer', 'Whole Number'), ('text', 'Text')], default='decimal', help_text='Type of value expected', max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum valid value (for decimal/integer fields)', max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum valid value (for decimal/integer fields)', max_digits=10, null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this field must be filled')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this field is shown in the form')),
                ('help_text_en', models.CharField(blank=True, default='', help_text='English helper tip for tailor', max_length=200)),
                ('help_text_ar', models.CharField(blank=True, default='', help_text='Arabic helper tip for tailor', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='Template this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='customization.measurementtemplate')),
            ],
            options={
                'verbose_name': 'Measurement Field',
                'verbose_name_plural': 'Measurement Fields',
                'ordering': ['template', 'display_order', 'name'],
                'unique_together': {('template', 'name')},
            },
        ),
    ]
