# Generated by Django 5.2.5 on 2026-06-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_measurementtemplate_measurementfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstyle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customstylecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='measurementfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='measurementtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userstylepreset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
