# Generated by Django 5.2.6 on 2025-12-04 07:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_add_rider_tailor_status_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Pickup location latitude (tailor location)', max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Pickup location longitude (tailor location)', max_digits=9, null=True)),
                ('pickup_address', models.TextField(blank=True, help_text='Formatted pickup address', null=True)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Delivery location latitude (customer address)', max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Delivery location longitude (customer address)', max_digits=9, null=True)),
                ('delivery_address', models.TextField(blank=True, help_text='Formatted delivery address', null=True)),
                ('current_status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('on_way_to_pickup', 'On Way to Pickup'), ('picked_up', 'Picked Up'), ('on_way_to_delivery', 'On Way to Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='assigned', help_text='Current delivery status', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When rider was assigned')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When rider accepted the order', null=True)),
                ('pickup_started_at', models.DateTimeField(blank=True, help_text='When rider started heading to pickup location', null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, help_text='When rider picked up the order', null=True)),
                ('delivery_started_at', models.DateTimeField(blank=True, help_text='When rider started heading to delivery location', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When order was delivered', null=True)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total distance traveled in kilometers', max_digits=10)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated distance from current location to destination in km', max_digits=10, null=True)),
                ('estimated_arrival_time', models.DateTimeField(blank=True, help_text='Estimated time of arrival at destination', null=True)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Last known latitude', max_digits=9, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Last known longitude', max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, help_text='When last location was updated', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the delivery', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tracking is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tracking', to='orders.order')),
                ('rider', models.ForeignKey(help_text='Rider assigned to this delivery', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Tracking',
                'verbose_name_plural': 'Delivery Tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='Location accuracy in meters (if available)', max_digits=8, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h (if available)', max_digits=8, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, help_text='Heading/bearing in degrees (0-360)', max_digits=5, null=True)),
                ('status', models.CharField(blank=True, help_text='Rider status at this location', max_length=30, null=True)),
                ('distance_from_previous', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Distance from previous location in km', max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_tracking', models.ForeignKey(help_text='Delivery tracking this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='deliveries.deliverytracking')),
            ],
            options={
                'verbose_name': 'Location History',
                'verbose_name_plural': 'Location Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverytracking',
            index=models.Index(fields=['order', 'is_active'], name='deliveries__order_i_ada9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytracking',
            index=models.Index(fields=['rider', 'is_active'], name='deliveries__rider_i_198c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytracking',
            index=models.Index(fields=['last_location_update'], name='deliveries__last_lo_cd5c62_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['delivery_tracking', '-created_at'], name='deliveries__deliver_6d16f9_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['created_at'], name='deliveries__created_ab74d3_idx'),
        ),
    ]
