# apps/tailors/services/order_pdf.py
"""
PDF generation service for tailor order download.
Supports English (default) and Arabic via Accept-Language header.
Requires: reportlab, arabic-reshaper, python-bidi
"""
import io
import os
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from django.utils import timezone

# ─── Arabic font registration ─────────────────────────────────────────────────
_FONTS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))),
    'fonts'
)
_AR_FONT_REGULAR = 'Amiri'
_AR_FONT_BOLD    = 'Amiri-Bold'

try:
    pdfmetrics.registerFont(TTFont(_AR_FONT_REGULAR, os.path.join(_FONTS_DIR, 'Amiri-Regular.ttf')))
    pdfmetrics.registerFont(TTFont(_AR_FONT_BOLD,    os.path.join(_FONTS_DIR, 'Amiri-Bold.ttf')))
    _ARABIC_FONT_AVAILABLE = True
except Exception:
    _ARABIC_FONT_AVAILABLE = False


# ─── Arabic text shaping helper ───────────────────────────────────────────────
def _shape_arabic(text):
    """
    Shape and reorder Arabic text for correct RTL rendering in ReportLab.
    Returns the visually-correct string.
    """
    if not text:
        return text
    try:
        import arabic_reshaper
        from bidi.algorithm import get_display
        reshaped = arabic_reshaper.reshape(str(text))
        return get_display(reshaped)
    except Exception:
        return text


# ─── Translation dictionary ───────────────────────────────────────────────────
_AR_LABELS = {
    # Section headers
    'ORDER DETAILS':       'تفاصيل الطلب',
    'CUSTOMER DETAILS':    'بيانات العميل',
    'TAILOR DETAILS':      'بيانات الخياط',
    'NOTES & INSTRUCTIONS':'الملاحظات والتعليمات',
    'ORDER ITEMS':         'عناصر الطلب',
    'RIDER MEASUREMENTS':  'قياسات المندوب',
    'PRICING SUMMARY':     'ملخص التسعير',
    'STATUS HISTORY':      'سجل الحالة',
    # Order info labels
    'Order Number':        'رقم الطلب',
    'Order Type':          'نوع الطلب',
    'Service Mode':        'طريقة الخدمة',
    'Payment Method':      'طريقة الدفع',
    'Payment Status':      'حالة الدفع',
    'Items Count':         'عدد العناصر',
    'Est. Delivery':       'التسليم المتوقع',
    'Actual Delivery':     'تاريخ التسليم',
    'Appointment':         'الموعد',
    'Stitching Done':      'تاريخ انتهاء الخياطة',
    # Customer labels
    'Customer Name':       'اسم العميل',
    'Phone':               'الهاتف',
    'Email':               'البريد الإلكتروني',
    'Delivery Addr.':      'عنوان التوصيل',
    'Extra Info':          'معلومات إضافية',
    'For (Family)':        'لصالح (عائلة)',
    'Relationship':        'صلة القرابة',
    # Tailor labels
    'Shop Name':           'اسم المحل',
    'Tailor':              'الخياط',
    'Contact':             'التواصل',
    'Assigned Rider':      'المندوب المخصص',
    # Notes labels
    'Special Instructions:': 'تعليمات خاصة:',
    'Internal Notes:':       'ملاحظات داخلية:',
    # Items table headers
    'Item / Fabric':       'العنصر / القماش',
    'For':                 'لصالح',
    'Qty':                 'الكمية',
    'Unit Price':          'سعر الوحدة',
    'Total Price':         'السعر الإجمالي',
    'Ready':               'جاهز',
    # Statuses
    'Status:':             'الحالة:',
    'Tailor Status:':      'حالة الخياط:',
    'Placed:':             'تاريخ الطلب:',
    # Pricing
    'Subtotal':            'المجموع الفرعي',
    'Stitching Price':     'سعر الخياطة',
    'Tax':                 'الضريبة',
    'Delivery Fee':        'رسوم التوصيل',
    'Platform Fee':        'رسوم المنصة',
    'TOTAL AMOUNT':        'المبلغ الإجمالي',
    # History headers
    'Date & Time':         'التاريخ والوقت',
    'Status':              'الحالة',
    'Changed By':          'تم التغيير بواسطة',
    'Notes':               'الملاحظات',
    # Header
    'Order Receipt':       'إيصال الطلب',
    # Footer
    'Generated by Mgask Platform': 'تم الإنشاء بواسطة منصة مقاسك',
    'Order':               'الطلب',
    # Misc
    'No items found for this order.': 'لا توجد عناصر لهذا الطلب.',
    'Instructions:':       'التعليمات:',
    'Measurements:':       'القياسات:',
    'Styles:':             'الأنماط:',
    'N/A':                 'غير متاح',
    'Measured at:':        'تم القياس في:',
    # Common measurement keys
    'Chest':               'الصدر',
    'Waist':               'الخصر',
    'Hips':                'الأرداف',
    'Shoulder':            'الكتف',
    'Sleeve':              'الكم',
    'Sleeve Length':       'طول الكم',
    'Length':              'الطول',
    'Neck':                'الرقبة',
    'Arm Hole':            'فتحة الإبط',
    'Cuff':                'الكم/الأسورة',
    'Thigh':               'الفخذ',
    'Inseam':              'طول الساق الداخلي',
    'Pocket':              'الجيب',
    'Collar':              'الياقة',
    'Back Width':          'عرض الظهر',
    'Front Width':         'عرض الصدر',
    'Bicep':               'العضلة',
    'Wrist':               'المعصم',
}


# ─── Brand colors ────────────────────────────────────────────────────────────
BRAND_PRIMARY   = colors.HexColor('#1A1A2E')   # Dark navy
BRAND_ACCENT    = colors.HexColor('#C9A84C')   # Gold
BRAND_LIGHT     = colors.HexColor('#F5F5F5')   # Light grey
BRAND_MID       = colors.HexColor('#DDDDDD')   # Divider grey
BRAND_TEXT      = colors.HexColor('#333333')   # Main text
BRAND_SUBTEXT   = colors.HexColor('#666666')   # Secondary text
WHITE           = colors.white


def _styles(lang='en'):
    """Return a dict of named ParagraphStyles, RTL-aware when lang='ar'."""
    base = getSampleStyleSheet()
    is_ar = lang == 'ar' and _ARABIC_FONT_AVAILABLE

    font_regular = _AR_FONT_REGULAR if is_ar else 'Helvetica'
    font_bold    = _AR_FONT_BOLD    if is_ar else 'Helvetica-Bold'
    body_align   = TA_RIGHT if is_ar else TA_LEFT

    return {
        'title': ParagraphStyle(
            f'Title_{lang}',
            parent=base['Normal'],
            fontSize=22,
            fontName=font_bold,
            textColor=WHITE,
            alignment=TA_RIGHT if is_ar else TA_LEFT,
            spaceAfter=2,
        ),
        'subtitle': ParagraphStyle(
            f'Subtitle_{lang}',
            parent=base['Normal'],
            fontSize=10,
            fontName=font_regular,
            textColor=colors.HexColor('#CCCCCC'),
            alignment=TA_LEFT if is_ar else TA_LEFT,
        ),
        'section_header': ParagraphStyle(
            f'SectionHeader_{lang}',
            parent=base['Normal'],
            fontSize=9,
            fontName=font_bold,
            textColor=BRAND_ACCENT,
            spaceBefore=6,
            spaceAfter=3,
            alignment=body_align,
        ),
        'label': ParagraphStyle(
            f'Label_{lang}',
            parent=base['Normal'],
            fontSize=8,
            fontName=font_bold,
            textColor=BRAND_SUBTEXT,
            alignment=body_align,
        ),
        'value': ParagraphStyle(
            f'Value_{lang}',
            parent=base['Normal'],
            fontSize=9,
            fontName=font_regular,
            textColor=BRAND_TEXT,
            alignment=body_align,
        ),
        'small': ParagraphStyle(
            f'Small_{lang}',
            parent=base['Normal'],
            fontSize=7.5,
            fontName=font_regular,
            textColor=BRAND_SUBTEXT,
            alignment=body_align,
        ),
        'footer': ParagraphStyle(
            f'Footer_{lang}',
            parent=base['Normal'],
            fontSize=7,
            fontName=font_regular,
            textColor=BRAND_SUBTEXT,
            alignment=TA_CENTER,
        ),
        'table_header': ParagraphStyle(
            f'TableHeader_{lang}',
            parent=base['Normal'],
            fontSize=8,
            fontName=font_bold,
            textColor=WHITE,
            alignment=body_align,
        ),
        'table_cell': ParagraphStyle(
            f'TableCell_{lang}',
            parent=base['Normal'],
            fontSize=8,
            fontName=font_regular,
            textColor=BRAND_TEXT,
            alignment=body_align,
        ),
        'total_label': ParagraphStyle(
            f'TotalLabel_{lang}',
            parent=base['Normal'],
            fontSize=9,
            fontName=font_bold,
            textColor=BRAND_TEXT,
            alignment=TA_RIGHT,
        ),
        'total_value': ParagraphStyle(
            f'TotalValue_{lang}',
            parent=base['Normal'],
            fontSize=10,
            fontName=font_bold,
            textColor=BRAND_ACCENT,
            alignment=TA_RIGHT,
        ),
    }


def _fmt_date(dt):
    """Safely format a date/datetime to a readable string."""
    if dt is None:
        return '—'
    try:
        if hasattr(dt, 'strftime'):
            return dt.strftime('%d %b %Y')
        return str(dt)
    except Exception:
        return str(dt)


def _fmt_datetime(dt):
    """Safely format a datetime to readable string with time."""
    if dt is None:
        return '—'
    try:
        if hasattr(dt, 'strftime'):
            return dt.strftime('%d %b %Y, %I:%M %p')
        return str(dt)
    except Exception:
        return str(dt)


def _fmt_amount(value, currency='SAR'):
    """Format a decimal/float as currency string."""
    if value is None:
        return f'{currency} 0.00'
    try:
        return f'{currency} {float(value):,.2f}'
    except (TypeError, ValueError):
        return f'{currency} {value}'


def _status_badge_color(status):
    """Return background color for status badge."""
    mapping = {
        'pending':           colors.HexColor('#FF9800'),
        'confirmed':         colors.HexColor('#2196F3'),
        'in_progress':       colors.HexColor('#9C27B0'),
        'ready_for_delivery':colors.HexColor('#009688'),
        'ready_for_pickup':  colors.HexColor('#009688'),
        'delivered':         colors.HexColor('#4CAF50'),
        'collected':         colors.HexColor('#4CAF50'),
        'cancelled':         colors.HexColor('#F44336'),
    }
    return mapping.get(status, BRAND_MID)


def _kv_table(rows, col_widths=None, lang='en'):
    """
    Build a compact key-value table.
    rows = list of (label_str, value_str) tuples.
    For RTL (Arabic), columns are swapped: value on left, label on right.
    """
    s = _styles(lang)
    is_ar = lang == 'ar'
    page_w = A4[0] - 40 * mm
    col_widths = col_widths or [page_w * 0.35, page_w * 0.65]

    if is_ar:
        # Swap col widths and cell order for RTL
        col_widths = list(reversed(col_widths))
        data = [
            [Paragraph(_t(val, lang), s['value']), Paragraph(_t(lbl, lang), s['label'])]
            for lbl, val in rows
        ]
    else:
        data = [
            [Paragraph(lbl, s['label']), Paragraph(str(val) if val else '—', s['value'])]
            for lbl, val in rows
        ]
    tbl = Table(data, colWidths=col_widths, hAlign='RIGHT' if is_ar else 'LEFT')
    tbl.setStyle(TableStyle([
        ('VALIGN',        (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING',    (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING',   (0, 0), (-1, -1), 0),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 6),
    ]))
    return tbl


def _t(text, lang):
    """Translate a label to Arabic and shape it for RTL rendering if lang='ar'."""
    if lang != 'ar':
        return str(text) if text else '—'
    arabic = _AR_LABELS.get(str(text), str(text)) if text else '—'
    return _shape_arabic(arabic)


def _measurements_grid(pairs, page_w, s, lang='en', title=''):
    """
    Render a list of (label, value) measurement pairs as a clean 3-column
    bordered card grid with an accent header row.

    Each card cell shows:
      ┌──────────────┐
      │  LABEL       │
      │  value cm    │
      └──────────────┘
    Numeric values automatically get a 'cm' unit appended.
    """
    is_ar = lang == 'ar'
    font_regular = _AR_FONT_REGULAR if (is_ar and _ARABIC_FONT_AVAILABLE) else 'Helvetica'
    font_bold    = _AR_FONT_BOLD    if (is_ar and _ARABIC_FONT_AVAILABLE) else 'Helvetica-Bold'
    align        = TA_RIGHT if is_ar else TA_LEFT

    lbl_style = ParagraphStyle(
        f'MeasLbl_{lang}', fontSize=7, fontName=font_bold,
        textColor=BRAND_ACCENT, alignment=align, spaceAfter=1,
    )
    val_style = ParagraphStyle(
        f'MeasVal_{lang}', fontSize=10, fontName=font_bold,
        textColor=BRAND_TEXT, alignment=align,
    )
    unit_style = ParagraphStyle(
        f'MeasUnit_{lang}', fontSize=7, fontName=font_regular,
        textColor=BRAND_SUBTEXT, alignment=align,
    )

    def _is_numeric(v):
        try:
            float(str(v).replace(',', ''))
            return True
        except ValueError:
            return False

    def _cell(lbl, val):
        lbl_text = _t(lbl, lang) if lang == 'ar' else lbl.upper()
        val_text = str(val)
        unit_text = 'cm' if _is_numeric(val) else ''
        inner = [
            [Paragraph(lbl_text, lbl_style)],
            [Paragraph(val_text, val_style)],
        ]
        if unit_text:
            inner.append([Paragraph(unit_text, unit_style)])
        inner_tbl = Table(inner, colWidths=['100%'])
        inner_tbl.setStyle(TableStyle([
            ('TOPPADDING',    (0, 0), (-1, -1), 1),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 1),
            ('LEFTPADDING',   (0, 0), (-1, -1), 0),
            ('RIGHTPADDING',  (0, 0), (-1, -1), 0),
        ]))
        return inner_tbl

    # Chunk pairs into rows of 3 cells each
    COLS = 3
    cell_w = page_w / COLS
    grid_rows = []

    # Optional title header row
    if title:
        title_text = _shape_arabic(title) if is_ar else title.upper()
        title_cell = Paragraph(title_text, ParagraphStyle(
            f'MeasTitle_{lang}', fontSize=8, fontName=font_bold,
            textColor=WHITE, alignment=TA_CENTER,
        ))
        title_row_tbl = Table([[title_cell]], colWidths=[page_w])
        title_row_tbl.setStyle(TableStyle([
            ('BACKGROUND',    (0, 0), (-1, -1), BRAND_PRIMARY),
            ('TOPPADDING',    (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('LEFTPADDING',   (0, 0), (-1, -1), 6),
            ('RIGHTPADDING',  (0, 0), (-1, -1), 6),
        ]))
        # We'll prepend this manually below

    # Reverse order for RTL so pairs read right-to-left
    if is_ar:
        pairs = list(reversed(pairs))

    for i in range(0, len(pairs), COLS):
        chunk = pairs[i:i + COLS]
        # Pad with empty cells to fill the row
        while len(chunk) < COLS:
            chunk.append(('', ''))
        grid_rows.append([_cell(lbl, val) if lbl else '' for lbl, val in chunk])

    if not grid_rows:
        return Paragraph('', s['value'])

    grid = Table(grid_rows, colWidths=[cell_w] * COLS)
    grid.setStyle(TableStyle([
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING',    (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING',   (0, 0), (-1, -1), 8),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 8),
        ('GRID',          (0, 0), (-1, -1), 0.5, BRAND_MID),
        ('ROWBACKGROUNDS',(0, 0), (-1, -1), [WHITE, BRAND_LIGHT]),
        ('LINEABOVE',     (0, 0), (-1, 0),  1, BRAND_ACCENT),
        ('LINEBELOW',     (0, -1),(-1, -1), 1, BRAND_MID),
    ]))

    if title:
        # Wrap grid with title header in an outer table
        outer = Table(
            [[title_row_tbl], [grid]],
            colWidths=[page_w]
        )
        outer.setStyle(TableStyle([
            ('TOPPADDING',    (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ('LEFTPADDING',   (0, 0), (-1, -1), 0),
            ('RIGHTPADDING',  (0, 0), (-1, -1), 0),
        ]))
        return outer

    return grid


def generate_order_pdf(order, lang='en') -> bytes:
    """
    Generate a professional PDF for a single order.

    Args:
        order: apps.orders.models.Order instance (with related objects pre-fetched or lazy).
        lang: Language code, 'en' (default) or 'ar' for Arabic RTL.

    Returns:
        bytes: Raw PDF file content.
    """
    is_ar = lang == 'ar'
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
        title=f'Order {order.order_number}',
        author='Mgask Platform',
    )

    s = _styles(lang)
    page_w = A4[0] - 40 * mm
    story = []

    # ── Header banner ─────────────────────────────────────────────────────────
    _receipt_label = _shape_arabic(_AR_LABELS['Order Receipt']) if is_ar else 'Order Receipt'
    _font_bold = _AR_FONT_BOLD if (is_ar and _ARABIC_FONT_AVAILABLE) else 'Helvetica-Bold'
    if is_ar:
        header_data = [[
            Paragraph(
                f'<b>{_receipt_label}</b><br/><font color="#CCCCCC">{order.order_number}</font>',
                ParagraphStyle(f'hr_{lang}', parent=s['subtitle'], alignment=TA_RIGHT, fontSize=10,
                               textColor=WHITE, fontName=_font_bold)
            ),
            Paragraph(_shape_arabic('مقاسك'), s['title']),
        ]]
    else:
        header_data = [[
            Paragraph('MGASK', s['title']),
            Paragraph(
                f'<b>Order Receipt</b><br/><font color="#CCCCCC">{order.order_number}</font>',
                ParagraphStyle(f'hr_{lang}', parent=s['subtitle'], alignment=TA_RIGHT, fontSize=10,
                               textColor=WHITE, fontName=_font_bold)
            ),
        ]]
    header_tbl = Table(header_data, colWidths=[page_w * 0.5, page_w * 0.5])
    header_tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, -1), BRAND_PRIMARY),
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING',    (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('LEFTPADDING',   (0, 0), (0, -1),  10),
        ('RIGHTPADDING',  (-1, 0), (-1, -1), 10),
        ('ROUNDEDCORNERS', [4, 4, 4, 4]),
    ]))
    story.append(header_tbl)
    story.append(Spacer(1, 5 * mm))

    # ── Status strip ──────────────────────────────────────────────────────────
    status_display  = order.get_status_display()
    tailor_status_display = order.get_tailor_status_display() if order.tailor_status else _t('N/A', lang)
    status_color = _status_badge_color(order.status)
    _sb_font = _AR_FONT_BOLD if (is_ar and _ARABIC_FONT_AVAILABLE) else 'Helvetica-Bold'

    _status_lbl  = _t('Status:', lang)
    _tailor_lbl  = _t('Tailor Status:', lang)
    _placed_lbl  = _t('Placed:', lang)

    status_data = [[
        Paragraph(f'{_status_lbl} <b>{_shape_arabic(status_display) if is_ar else status_display}</b>',
                  ParagraphStyle(f'sb_{lang}', parent=s['value'], fontSize=9, textColor=WHITE, fontName=_sb_font,
                                 alignment=TA_RIGHT if is_ar else TA_LEFT)),
        Paragraph(f'{_tailor_lbl} <b>{_shape_arabic(tailor_status_display) if is_ar else tailor_status_display}</b>',
                  ParagraphStyle(f'sb2_{lang}', parent=s['value'], fontSize=9, textColor=WHITE, fontName=_sb_font,
                                 alignment=TA_CENTER)),
        Paragraph(f'{_placed_lbl} <b>{_fmt_datetime(order.created_at)}</b>',
                  ParagraphStyle(f'sb3_{lang}', parent=s['value'], fontSize=9, textColor=WHITE, fontName=_sb_font,
                                 alignment=TA_LEFT if is_ar else TA_RIGHT)),
    ]]
    if is_ar:
        status_data[0].reverse()
    status_tbl = Table(status_data, colWidths=[page_w / 3] * 3)
    status_tbl.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, -1), status_color),
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING',    (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING',   (0, 0), (-1, -1), 8),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 8),
    ]))
    story.append(status_tbl)
    story.append(Spacer(1, 5 * mm))

    # ── Two-column: Order Info + Customer Info ────────────────────────────────
    # Order Info
    order_type_display = order.get_order_type_display()
    service_mode_display = order.get_service_mode_display()
    payment_status_display = order.get_payment_status_display()
    payment_method_display = order.get_payment_method_display()

    order_info_rows = [
        ('Order Number',     order.order_number),
        ('Order Type',       order_type_display),
        ('Service Mode',     service_mode_display),
        ('Payment Method',   payment_method_display),
        ('Payment Status',   payment_status_display),
        ('Items Count',      str(order.items_count)),
    ]
    if order.estimated_delivery_date:
        order_info_rows.append(('Est. Delivery', _fmt_date(order.estimated_delivery_date)))
    if order.actual_delivery_date:
        order_info_rows.append(('Actual Delivery', _fmt_date(order.actual_delivery_date)))
    if order.appointment_date:
        appt = _fmt_date(order.appointment_date)
        if order.appointment_time:
            appt += f' at {order.appointment_time.strftime("%I:%M %p")}'
        order_info_rows.append(('Appointment', appt))
    if order.stitching_completion_date:
        order_info_rows.append(('Stitching Done', _fmt_date(order.stitching_completion_date)))

    # Customer Info
    customer = order.customer
    customer_name = customer.get_full_name() or customer.username if customer else '—'
    customer_phone = getattr(customer, 'phone', None) or '—'
    customer_email = getattr(customer, 'email', '') or '—'

    # Delivery address
    addr_text = '—'
    if order.delivery_formatted_address:
        addr_text = order.delivery_formatted_address
    elif order.delivery_address:
        a = order.delivery_address
        parts = filter(None, [a.street, a.city, a.country])
        addr_text = ', '.join(parts)
    elif order.delivery_street:
        parts = filter(None, [order.delivery_street, order.delivery_city])
        addr_text = ', '.join(parts)

    customer_rows = [
        ('Customer Name',  customer_name),
        ('Phone',          customer_phone),
        ('Email',          customer_email),
        ('Delivery Addr.', addr_text),
    ]
    if order.delivery_extra_info:
        customer_rows.append(('Extra Info', order.delivery_extra_info))

    # Family member
    if order.family_member:
        fm = order.family_member
        customer_rows.append(('For (Family)', fm.name))
        if fm.relationship:
            customer_rows.append(('Relationship', fm.relationship))

    col_half = page_w / 2 - 3 * mm

    def _section_block(title_str, kv_rows, col_w):
        inner = []
        inner.append(Paragraph(_t(title_str, lang), s['section_header']))
        inner.append(HRFlowable(width=col_w, color=BRAND_ACCENT, thickness=0.5, spaceAfter=4))
        inner.append(_kv_table(kv_rows, col_widths=[col_w * 0.42, col_w * 0.58], lang=lang))
        return inner

    # Combine in 2-col table (swap columns for Arabic RTL)
    order_block    = _section_block('ORDER DETAILS', order_info_rows, col_half)
    customer_block = _section_block('CUSTOMER DETAILS', customer_rows, col_half)
    left_cell, right_cell = (customer_block, order_block) if is_ar else (order_block, customer_block)

    two_col = Table([[left_cell, right_cell]], colWidths=[col_half, col_half + 6 * mm])
    two_col.setStyle(TableStyle([
        ('VALIGN',       (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING',  (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING',   (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING',(0, 0), (-1, -1), 0),
        ('LINEAFTER',    (0, 0), (0, -1),  0.5, BRAND_MID),
        ('RIGHTPADDING', (0, 0), (0, -1),  6),
        ('LEFTPADDING',  (1, 0), (1, -1),  6),
    ]))
    story.append(two_col)
    story.append(Spacer(1, 5 * mm))

    # ── Tailor Info ───────────────────────────────────────────────────────────
    tailor = order.tailor
    if tailor:
        story.append(Paragraph(_t('TAILOR DETAILS', lang), s['section_header']))
        story.append(HRFlowable(width=page_w, color=BRAND_ACCENT, thickness=0.5, spaceAfter=4))

        tailor_name = tailor.get_full_name() or tailor.username
        shop_name = '—'
        tailor_contact = getattr(tailor, 'phone', None) or '—'

        try:
            profile = tailor.tailor_profile
            shop_name = profile.shop_name or tailor_name
            tailor_contact = profile.contact_number or tailor_contact
        except Exception:
            pass

        tailor_rows = [
            ('Shop Name',  shop_name),
            ('Tailor',     tailor_name),
            ('Contact',    tailor_contact),
        ]
        if order.assigned_rider:
            rider = order.assigned_rider
            tailor_rows.append(('Assigned Rider', rider.get_full_name() or rider.username))

        story.append(_kv_table(tailor_rows, lang=lang))
        story.append(Spacer(1, 4 * mm))

    # ── Special instructions / notes ──────────────────────────────────────────
    if order.special_instructions or order.notes:
        story.append(Paragraph(_t('NOTES & INSTRUCTIONS', lang), s['section_header']))
        story.append(HRFlowable(width=page_w, color=BRAND_ACCENT, thickness=0.5, spaceAfter=4))
        if order.special_instructions:
            _si_label = _t('Special Instructions:', lang)
            _si_text  = _shape_arabic(order.special_instructions) if is_ar else order.special_instructions
            story.append(Paragraph(f'<b>{_si_label}</b> {_si_text}', s['value']))
            story.append(Spacer(1, 2 * mm))
        if order.notes:
            _n_label = _t('Internal Notes:', lang)
            _n_text  = _shape_arabic(order.notes) if is_ar else order.notes
            story.append(Paragraph(f'<b>{_n_label}</b> {_n_text}', s['value']))
        story.append(Spacer(1, 4 * mm))

    # ── Order Items table ─────────────────────────────────────────────────────
    story.append(Paragraph(_t('ORDER ITEMS', lang), s['section_header']))
    story.append(HRFlowable(width=page_w, color=BRAND_ACCENT, thickness=0.5, spaceAfter=4))

    items = list(order.order_items.select_related('fabric', 'family_member').all())

    if items:
        col_widths_items = [
            page_w * 0.28,  # Item / Fabric
            page_w * 0.18,  # For (recipient)
            page_w * 0.08,  # Qty
            page_w * 0.15,  # Unit Price
            page_w * 0.15,  # Total Price
            page_w * 0.16,  # Status
        ]

        item_headers = [
            Paragraph(_t('Item / Fabric', lang), s['table_header']),
            Paragraph(_t('For', lang), s['table_header']),
            Paragraph(_t('Qty', lang), s['table_header']),
            Paragraph(_t('Unit Price', lang), s['table_header']),
            Paragraph(_t('Total Price', lang), s['table_header']),
            Paragraph(_t('Ready', lang), s['table_header']),
        ]
        if is_ar:
            item_headers.reverse()
        item_rows = [item_headers]

        for item in items:
            fabric_name = item.fabric.name if item.fabric else 'Measurement Service'
            fabric_sku  = f'SKU: {item.fabric.sku}' if item.fabric and item.fabric.sku else ''
            fabric_cell = Paragraph(
                f'{fabric_name}<br/><font color="#888888" size="7">{fabric_sku}</font>',
                s['table_cell']
            )

            recipient = '—'
            if item.family_member:
                recipient = item.family_member.name
            elif customer:
                recipient = customer_name

            is_ready = ('✓ ' + (_shape_arabic('نعم') if is_ar else 'Yes')) if item.is_ready \
                  else ('✗ ' + (_shape_arabic('لا')  if is_ar else 'No'))
            ready_color = colors.HexColor('#4CAF50') if item.is_ready else colors.HexColor('#F44336')
            _item_font_bold = _AR_FONT_BOLD if (is_ar and _ARABIC_FONT_AVAILABLE) else 'Helvetica-Bold'

            row = [
                fabric_cell,
                Paragraph(_shape_arabic(recipient) if is_ar else recipient, s['table_cell']),
                Paragraph(str(item.quantity), s['table_cell']),
                Paragraph(_fmt_amount(item.unit_price), s['table_cell']),
                Paragraph(_fmt_amount(item.total_price), s['table_cell']),
                Paragraph(is_ready, ParagraphStyle(
                    f'is_ready_{lang}', parent=s['table_cell'],
                    textColor=ready_color, fontName=_item_font_bold
                )),
            ]
            if is_ar:
                row.reverse()
            item_rows.append(row)

            # Extra info rows (Instructions, Measurements, Styles)
            # We use an empty list for spanned columns [Content, '', '', '', '', '']
            
            # 1. Custom instructions row
            if item.custom_instructions:
                _instr_label = _t('Instructions:', lang)
                _instr_text  = _shape_arabic(item.custom_instructions) if is_ar else item.custom_instructions
                instr_p = Paragraph(f'<b>{_instr_label}</b> {_instr_text}', s['small'])
                item_rows.append([instr_p, '', '', '', '', ''])

            # 2. Measurements row — rendered as a professional grid
            if item.measurements and isinstance(item.measurements, dict):
                meas_pairs = [
                    (str(k).replace('_', ' ').title(), v)
                    for k, v in item.measurements.items()
                    if k != 'title' and v not in (None, '', 'null')
                ]
                if meas_pairs:
                    meas_title = item.measurements.get('title', '')
                    grid = _measurements_grid(meas_pairs, page_w, s, lang, title=meas_title)
                    item_rows.append([grid, '', '', '', '', ''])

            # 3. Custom styles row
            if item.custom_styles and isinstance(item.custom_styles, list):
                style_texts = [
                    f'{cs.get("style_type", "").replace("_", " ").title()}: {cs.get("label", "")}'
                    for cs in item.custom_styles if cs.get('label')
                ]
                if style_texts:
                    _styles_label = _t('Styles:', lang)
                    _styles_text = ',  '.join(style_texts)
                    if is_ar:
                        _styles_text = _shape_arabic(_styles_text)
                    style_p = Paragraph(f'<b>{_styles_label}</b> {_styles_text}', s['small'])
                    item_rows.append([style_p, '', '', '', '', ''])

        items_tbl = Table(item_rows, colWidths=col_widths_items, repeatRows=1)
        
        # Build style list
        tbl_style = [
            ('BACKGROUND',    (0, 0), (-1, 0),  BRAND_PRIMARY),
            ('TOPPADDING',    (0, 0), (-1, 0),  6),
            ('BOTTOMPADDING', (0, 0), (-1, 0),  6),
            ('VALIGN',        (0, 0), (-1, -1), 'TOP'),
            ('GRID',          (0, 0), (-1, -1), 0.3, BRAND_MID),
            ('LINEBELOW',     (0, 0), (-1, 0),  1,   BRAND_ACCENT),
        ]

        # Apply SPAN and special styling for info rows
        for idx, row in enumerate(item_rows):
            if idx == 0: continue # Header
            # Check if this is an info row (has only one real content in index 0 or index -1 for RTL)
            # In our case we always put content in index 0 then reverse, so content is at idx 0 or 5.
            # But the SPAN logic in ReportLab always uses absolute indices 0..N.
            
            # Simple heuristic: if index 1..4 are empty strings, it's a spanned row
            if row[1] == '' and row[2] == '' and row[3] == '' and row[4] == '':
                tbl_style.append(('SPAN', (0, idx), (5, idx)))
                # Set background for measurement grid to distinguish it
                if not isinstance(row[0], Paragraph):
                    tbl_style.append(('BACKGROUND', (0, idx), (5, idx), BRAND_LIGHT))
                    tbl_style.append(('TOPPADDING',    (0, idx), (5, idx), 2))
                    tbl_style.append(('BOTTOMPADDING', (0, idx), (5, idx), 2))
                else:
                    # It's a text info row (Instructions/Styles)
                    tbl_style.append(('LEFTPADDING', (0, idx), (5, idx), 15))
                    tbl_style.append(('TOPPADDING',    (0, idx), (5, idx), 2))
                    tbl_style.append(('BOTTOMPADDING', (0, idx), (5, idx), 2))
            else:
                # Main item row
                bg_color = WHITE if (idx % 2 == 1) else BRAND_LIGHT
                tbl_style.append(('BACKGROUND', (0, idx), (-1, idx), bg_color))

        items_tbl.setStyle(TableStyle(tbl_style))
        story.append(items_tbl)
    else:
        story.append(Paragraph(_t('No items found for this order.', lang), s['value']))

    story.append(Spacer(1, 6 * mm))

    # ── Order-level measurements (rider measurements) ─────────────────────────
    if order.rider_measurements and isinstance(order.rider_measurements, dict) and order.rider_measurements:
        story.append(Paragraph(_t('RIDER MEASUREMENTS', lang), s['section_header']))
        story.append(HRFlowable(width=page_w, color=BRAND_ACCENT, thickness=0.5, spaceAfter=4))
        if order.measurement_taken_at:
            story.append(Paragraph(
                f'<i>{_t("Measured at:", lang)} {_fmt_datetime(order.measurement_taken_at)}</i>',
                s['small']
            ))
            story.append(Spacer(1, 2 * mm))
        meas_pairs = [
            (str(k).replace('_', ' ').title(), str(v))
            for k, v in order.rider_measurements.items()
            if v not in (None, '', 'null')
        ]
        story.append(_measurements_grid(meas_pairs, page_w, s, lang))
        story.append(Spacer(1, 5 * mm))



    # ── Pricing Summary ───────────────────────────────────────────────────────
    story.append(Paragraph(_t('PRICING SUMMARY', lang), s['section_header']))
    story.append(HRFlowable(width=page_w, color=BRAND_ACCENT, thickness=0.5, spaceAfter=4))

    price_rows = []

    def _price_row(label, amount, bold=False, accent=False):
        lbl_style = ParagraphStyle('pl', parent=s['label'], alignment=TA_RIGHT,
                                    fontName='Helvetica-Bold' if bold else 'Helvetica')
        val_style = ParagraphStyle('pv', parent=s['value'], alignment=TA_RIGHT,
                                    fontSize=10 if bold else 9,
                                    textColor=BRAND_ACCENT if accent else BRAND_TEXT,
                                    fontName='Helvetica-Bold' if bold else 'Helvetica')
        return [Paragraph('', s['label']), Paragraph(label, lbl_style),
                Paragraph(_fmt_amount(amount), val_style)]

    price_rows.append(_price_row(_t('Subtotal', lang), order.subtotal))
    if order.stitching_price:
        price_rows.append(_price_row(_t('Stitching Price', lang), order.stitching_price))
    if order.tax_amount:
        price_rows.append(_price_row(_t('Tax', lang), order.tax_amount))
    if order.delivery_fee:
        price_rows.append(_price_row(_t('Delivery Fee', lang), order.delivery_fee))
    if order.system_fee:
        price_rows.append(_price_row(_t('Platform Fee', lang), order.system_fee))

    # Divider row
    price_rows.append([
        Paragraph('', s['label']),
        HRFlowable(width=page_w * 0.35, color=BRAND_MID, thickness=0.5),
        HRFlowable(width=page_w * 0.25, color=BRAND_MID, thickness=0.5),
    ])
    price_rows.append(_price_row(_t('TOTAL AMOUNT', lang), order.total_amount, bold=True, accent=True))

    pricing_tbl = Table(
        price_rows,
        colWidths=[page_w * 0.40, page_w * 0.35, page_w * 0.25],
        hAlign='RIGHT'
    )
    pricing_tbl.setStyle(TableStyle([
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING',    (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING',   (0, 0), (-1, -1), 0),
        ('RIGHTPADDING',  (0, 0), (-1, -1), 0),
        ('BACKGROUND',    (0, -1), (-1, -1), BRAND_LIGHT),
    ]))
    story.append(pricing_tbl)
    story.append(Spacer(1, 6 * mm))

    # ── Status History ────────────────────────────────────────────────────────
    history_qs = order.status_history.select_related('changed_by').order_by('created_at')[:20]
    history = list(history_qs)

    if history:
        story.append(Paragraph(_t('STATUS HISTORY', lang), s['section_header']))
        story.append(HRFlowable(width=page_w, color=BRAND_ACCENT, thickness=0.5, spaceAfter=4))

        hist_headers = [
            Paragraph(_t('Date & Time', lang), s['table_header']),
            Paragraph(_t('Status', lang), s['table_header']),
            Paragraph(_t('Changed By', lang), s['table_header']),
            Paragraph(_t('Notes', lang), s['table_header']),
        ]
        if is_ar:
            hist_headers.reverse()
        hist_rows = [hist_headers]

        for h in history:
            changed_by = h.changed_by.get_full_name() or h.changed_by.username if h.changed_by else '—'
            hist_row = [
                Paragraph(_fmt_datetime(h.created_at), s['small']),
                Paragraph(h.get_status_display(), s['small']),
                Paragraph(_shape_arabic(changed_by) if is_ar else changed_by, s['small']),
                Paragraph(_shape_arabic(h.notes or '—') if is_ar else (h.notes or '—'), s['small']),
            ]
            if is_ar:
                hist_row.reverse()
            hist_rows.append(hist_row)

        hist_tbl = Table(
            hist_rows,
            colWidths=[page_w * 0.25, page_w * 0.20, page_w * 0.22, page_w * 0.33],
            repeatRows=1
        )
        hist_tbl.setStyle(TableStyle([
            ('BACKGROUND',    (0, 0), (-1, 0),  BRAND_PRIMARY),
            ('TOPPADDING',    (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('LEFTPADDING',   (0, 0), (-1, -1), 5),
            ('RIGHTPADDING',  (0, 0), (-1, -1), 5),
            ('VALIGN',        (0, 0), (-1, -1), 'TOP'),
            ('GRID',          (0, 0), (-1, -1), 0.3, BRAND_MID),
            ('LINEBELOW',     (0, 0), (-1, 0),  1,   BRAND_ACCENT),
            ('ROWBACKGROUNDS',(0, 1), (-1, -1), [WHITE, BRAND_LIGHT]),
        ]))
        story.append(hist_tbl)
        story.append(Spacer(1, 5 * mm))

    # ── Footer ────────────────────────────────────────────────────────────────
    story.append(HRFlowable(width=page_w, color=BRAND_MID, thickness=0.5, spaceAfter=4))
    generated_time = timezone.now().strftime('%d %b %Y, %I:%M %p')
    if is_ar:
        _gen_label = _shape_arabic(_AR_LABELS['Generated by Mgask Platform'])
        _order_label = _shape_arabic(_AR_LABELS['Order'])
        footer_text = f'{_order_label} {order.order_number}  ·  {generated_time}  ·  {_gen_label}'
    else:
        footer_text = f'Generated by Mgask Platform  ·  {generated_time}  ·  Order {order.order_number}'
    story.append(Paragraph(footer_text, s['footer']))

    # Build PDF
    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
