# Generated by Django 5.2.6 on 2025-11-17 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(help_text='FCM device token', unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], default='android', help_text='Type of device', max_length=10)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active')),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Last time this token was used')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who owns this device token', on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCM Device Token',
                'verbose_name_plural': 'FCM Device Tokens',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('ORDER_STATUS', 'Order Status'), ('PAYMENT', 'Payment'), ('RIDER_ASSIGNMENT', 'Rider Assignment'), ('PROFILE', 'Profile'), ('APPOINTMENT', 'Appointment'), ('SYSTEM', 'System')], help_text='Type of notification', max_length=20)),
                ('category', models.CharField(help_text='Notification category (e.g., order_confirmed, payment_received)', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('body', models.TextField(help_text='Notification body/message')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', help_text='Status of notification delivery', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error message if notification failed', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fcm_token', models.ForeignKey(blank=True, help_text='FCM token used to send notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='notifications.fcmdevicetoken')),
                ('user', models.ForeignKey(help_text='User who received the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fcmdevicetoken',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_514985_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmdevicetoken',
            index=models.Index(fields=['token'], name='notificatio_token_edf1ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fcmdevicetoken',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_d1d348_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type', 'status'], name='notificatio_notific_219496_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='notificatio_created_01830a_idx'),
        ),
    ]
