# Generated by Django 5.2.6 on 2025-12-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationlog_is_read_read_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_user_id_d9b354_idx',
            old_name='notificatio_user_id_read_idx',
        ),
    ]
