# Generated by Django 5.2.5 on 2026-02-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_notificatio_user_id_read_idx_notificatio_user_id_d9b354_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_STATUS', 'Order Status'), ('PAYMENT', 'Payment'), ('RIDER_ASSIGNMENT', 'Rider Assignment'), ('PROFILE', 'Profile'), ('APPOINTMENT', 'Appointment'), ('SYSTEM', 'System'), ('PROMOTION', 'Promotion')], help_text='Type of notification', max_length=20),
        ),
    ]
