# Generated by Django 5.2.5 on 2026-05-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationlog_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_STATUS', 'Order Status'), ('PAYMENT', 'Payment'), ('RIDER_ASSIGNMENT', 'Rider Assignment'), ('PROFILE', 'Profile'), ('APPOINTMENT', 'Appointment'), ('SYSTEM', 'System'), ('PROMOTION', 'Promotion'), ('STYLE_CONSENT', 'Style Consent'), ('TEST', 'Test')], help_text='Type of notification', max_length=20),
        ),
    ]
