# Generated by Django 5.2.5 on 2026-05-13 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notificationlog_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcmdevicetoken',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fcmdevicetoken',
            name='app_role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('TAILOR', 'Tailor'), ('RIDER', 'Rider')], default='CUSTOMER', help_text='The app role associated with this token', max_length=20),
        ),
        migrations.AlterField(
            model_name='fcmdevicetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='fcmdevicetoken',
            unique_together={('user', 'device_id', 'app_role')},
        ),
    ]
